- type: entity
  id: CircuitImprinterLawBoardMatrixMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: lawboard matrix imprinter machine board
  components:
  - type: Sprite
    state: science
  - type: MachineBoard
    prototype: CircuitImprinterLawboard
    stackRequirements:
      MatterBin: 1
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker
      PotatoAIChip:
        amount: 1
        defaultPrototype: PotatoAIChip
