- type: entity
  parent: CrateGenericSteel
  id: CrateServiceColorfulLights
  name: colorful lights crate
  description: It's not a party until it's hard to see, a little disorienting, and your ears hurt.
  components:
  - type: StorageFill
    contents:
      - id: BoxLightbulbColorfulMixed
      - id: BoxLighttubeColorfulMixed
