- type: gameMap
  id: Meta
  mapName: 'Meta Station'
  mapPath: /Maps/meta.yml
  minPlayers: 45
  maxPlayers: 80
  stations:
    Meta:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: '{0} Meta Station {1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'TG'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_meta.yml
        - type: StationJobs
          availableJobs: # 63 jobs total roundstart, 81 jobs total w/ latejoins, 97 jobs w/ latejoins and interns.
            # Command (7)
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            HeadOfSecurity: [ 1, 1 ]
            ChiefMedicalOfficer: [ 1, 1 ]
            ChiefEngineer: [ 1, 1 ]
            ResearchDirector: [ 1, 1 ]
            Quartermaster: [ 1, 1 ]
            # Service (13 - 16)
            Bartender: [ 2, 2 ]
            Botanist: [ 2, 3 ]
            Chef: [ 2, 2 ]
            Janitor: [ 2, 3 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 2 ]
            Reporter: [ 1, 2 ]
            # Engineering (7 - 10)
            AtmosphericTechnician: [ 3, 3 ]
            StationEngineer: [ 4, 7 ]
            TechnicalAssistant: [ 4, 4 ] #intern, not counted
            # Medical (8 - 11)
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 4, 5 ]
            MedicalIntern: [ 4, 4 ] #intern, not counted
            Paramedic: [ 1, 2 ]
            Psychologist: [ 1, 1 ]
            # Science (5 - 7)
            Scientist: [ 5, 7 ]
            ResearchAssistant: [ 4, 4 ] #intern, not counted
            # Security (8 - 11)
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 5, 7 ]
            Detective: [ 1, 1 ]
            SecurityCadet: [ 4, 4 ] #intern, not counted
            Lawyer: [ 1, 2 ]
            # Supply (7 - 9)
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 4, 6 ]
            # Civilian (3+)
            Passenger: [ -1, -1 ] #infinite, not counted
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            # Silicon (5 - 7)
            StationAi: [ 1, 1 ]
            Borg: [ 4, 6 ]
