- type: gameMap
  id: Train
  mapName: 'Train'
  mapPath: /Maps/train.yml
  maxRandomOffset: 0
  randomRotation: false
  minPlayers: 35
  maxPlayers: 70
  stations:
    Train:
      stationProto: StandardNanotrasenStation
      components:
        - type: StationNameSetup
          mapNameTemplate: 'Train "Sentipode" {0}-{1}'
          nameGenerator:
            !type:NanotrasenNameGenerator
            prefixCreator: 'ED'
        - type: StationEmergencyShuttle
          emergencyShuttlePath: /Maps/Shuttles/emergency_omega.yml # TODO - add railway station
        - type: StationJobs
          availableJobs: # 53 jobs total w/o latejoins & interns, 65 jobs total w/ latejoins & interns
            #command (7)
            Captain: [ 1, 1 ]
            HeadOfPersonnel: [ 1, 1 ]
            HeadOfSecurity: [ 1, 1 ]
            ChiefMedicalOfficer: [ 1, 1 ]
            ChiefEngineer: [ 1, 1 ]
            ResearchDirector: [ 1, 1 ]
            Quartermaster: [ 1, 1 ]
            #service (11 - 12)
            Bartender: [ 1, 1 ]
            Botanist: [ 2, 2 ]
            Chef: [ 1, 1 ]
            Janitor: [ 2, 2 ]
            Chaplain: [ 1, 1 ]
            Librarian: [ 1, 1 ]
            ServiceWorker: [ 2, 3 ]
            Reporter: [ 1, 1 ]
            #engineering (6)
            AtmosphericTechnician: [ 2, 2 ]
            StationEngineer: [ 4, 5 ] #CD - Intern not counted
            # TechnicalAssistant: [ 3, 3 ] #CD - Remove intern roles, rework them into loadouts
            #medical (5)
            Chemist: [ 2, 2 ]
            MedicalDoctor: [ 2, 3 ] #CD - Intern not counted
            # MedicalIntern: [ 2, 2 ] #CD - Remove intern roles, rework them into loadouts
            Paramedic: [ 1, 1 ]
            #science (4)
            Scientist: [ 4, 5 ] #CD - Intern not counted
            # ResearchAssistant: [ 2, 2 ] #CD - Remove intern roles, rework them into loadouts
            #security (9 - 10)
            Warden: [ 1, 1 ]
            SecurityOfficer: [ 6, 7 ] #CD - Intern not counted
            # SecurityCadet: [ 3, 3 ] #CD - Remove intern roles, rework them into loadouts
            Lawyer: [ 1, 2 ]
            Detective: [ 1, 1 ]
            #supply (6)
            SalvageSpecialist: [ 3, 3 ]
            CargoTechnician: [ 3, 3 ]
            #civilian (3+)
            Passenger: [ -1, -1 ] #infinite, not counted
            Clown: [ 1, 1 ]
            Mime: [ 1, 1 ]
            Musician: [ 1, 1 ]
            #silicon (2)
            Borg: [ 2, 2 ]
            # Moffstation - custom roles below
            Prisoner: [ 1, 1 ]
