using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.SprayPainter.UI;

[GenerateTypedNameReferences, UsedImplicitly]
public sealed partial class SprayPainterWindow : DefaultWindow
{
    public void AddTab(Control child, string title)
    {
        Tabs.AddChild(child);
        Tabs.SetTabTitle(Tabs.ChildCount - 1, title);
    }
}
