# Pirates
- type: entity
  parent: BaseMindRoleAntag
  id: MindRolePirateCrew
  name: Pirate Crew Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    exclusiveAntag: true
    antagPrototype: PirateCrew
  - type: PirateRole

- type: entity
  parent: MindRolePirateCrew
  id: MindRolePirateMedic
  name: Pirate Medic Role
  components:
  - type: MindRole
    antagPrototype: PirateMedic

- type: entity
  parent: MindRolePirateCrew
  id: MindRolePirateCaptain
  name: Pirate Captain Role
  components:
  - type: MindRole
    antagPrototype: PirateCaptain

# Vampires

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVampire
  name: Vampire Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    exclusiveAntag: true
    antagPrototype: Vampire
  - type: VampireRole
