# Pirates
- type: entity
  parent: BaseMindRoleAntag
  id: MindRolePirate
  name: Pirate Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-pirate
    exclusiveAntag: true
    antagPrototype: Pirate
  - type: PirateRole

- type: entity
  parent: MindRolePirate
  id: MindRolePirateCaptain
  name: Pirate Captain Role
  components:
  - type: MindRole
    antagPrototype: PirateCaptain

# Vampires

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVampire
  name: Vampire Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    exclusiveAntag: true
    antagPrototype: Vampire
  - type: VampireRole
