using Content.Shared._DV.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Options.UI;

[GenerateTypedNameReferences]
public sealed partial class ForkSpecificTab : Control
{
    public ForkSpecificTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(DCCVars.EsScreenshakeDisabled, DisableScreenshakeCheckBox); // DeltaV - ES Screenshake Port
    }
}
