using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.ReadyManifest.UI;

[GenerateTypedNameReferences]
public sealed partial class ReadyManifestEntry : GridContainer
{
    public ReadyManifestEntry(
        JobPrototype job,
       (int High, int Medium, int Low) jobCount,
        IPrototypeManager prototypeManager,
        SpriteSystem spriteSystem)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        EntryTitle.SetMessage(job.LocalizedName + ":");

        var jobIcon = prototypeManager.Index(job.Icon);
        EntryIcon.Texture = spriteSystem.Frame0(jobIcon.Icon);

        HighReadyCount.SetMessage(jobCount.High.ToString());
        MedReadyCount.SetMessage(jobCount.Medium.ToString());
        LowReadyCount.SetMessage(jobCount.Low.ToString());
    }
}
