# SPDX-FileCopyrightText: 2025 Southbridge <7013162+southbridge-fur@users.noreply.github.com>
# SPDX-License-Identifier: MIT

- type: entity
  parent: MarkerBase
  id: DecalSpawnerBase
  name: Decal Spawner
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: green
    - state: decal
