# SPDX-FileCopyrightText: 2025 Southbridge
# SPDX-License-Identifier: MIT

- type: entity
  parent: MarkerBase
  id: DecalSpawnerBase
  name: Decal Spawner
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: green
    - state: decal
