# Nukie Reinforcement Gear. Needs to add the stuff that is normally covered by loadouts
- type: startingGear
  id: SyndicateOperativeReinforcementGear
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    gloves: ClothingHandsGlovesCombat
