- type: antag
  id: PirateCrew
  name: roles-antag-pirate-crew-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pirate-crew-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ NuclearOperatives ]

- type: antag
  id: PirateMedic
  name: roles-antag-pirate-medic-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pirate-medic-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ NuclearOperatives ]

- type: antag
  id: PirateCaptain
  name: roles-antag-pirate-captain-name
  antagonist: true
  setPreference: true
  objective: roles-antag-pirate-captain-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ NuclearOperatives ]
