using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.GaussFabricator;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.GaussFabricator;

[GenerateTypedNameReferences]
public sealed partial class GaussFabricatorWindow : FancyWindow
{
    [Dependency] private ILocalizationManager _loc = default!;

    public event Action<float>? OnAdjustDrawRate;
    public event Action<bool>? OnToggle;

    private static readonly Color ReceivedColor = Color.FromHex("#4499ff");
    private static readonly Color DrawGapColor = Color.FromHex("#1a4a8a");

    private readonly ButtonGroup _toggleGroup = new();

    // Reused so the progress bar isn't allocating a style box every frame
    private readonly StyleBoxFlat _progressStyle = new();

    // Draw adjustment button increments in watts, from largest to smallest
    private readonly float[] _increments = [50000f, 10000f, 1000f];

    private float _drawRate;
    private float _received;
    private float _targetProgress;
    private float _displayedProgress;

    public GaussFabricatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateButtons();

        TemperatureBar.NoDataText = _loc.GetString("gauss-fabricator-window-no-data");
        PressureBar.NoDataText = _loc.GetString("gauss-fabricator-window-no-data");

        OutputProgressBar.ForegroundStyleBoxOverride = _progressStyle;

        OnButton.Group = _toggleGroup;
        OffButton.Group = _toggleGroup;
        OnButton.OnPressed += _ => OnToggle?.Invoke(true);
        OffButton.OnPressed += _ => OnToggle?.Invoke(false);
    }

    public void UpdateSettings(GaussFabricatorComponent comp)
    {
        _drawRate = comp.DrawRate;
        DrawRateLabel.Text = FormatPower(comp.DrawRate);
        DrawLevelBar.Capacity = comp.MaxDrawRate;
        TemperatureBar.SetRanges(comp.TemperatureAcceptable, comp.TemperatureOptimal);
        PressureBar.SetRanges(comp.PressureAcceptable, comp.PressureOptimal);

        if (comp.Enabled)
            OnButton.Pressed = true;
        else
            OffButton.Pressed = true;

        UpdateDrawLevel();
    }

    public void UpdateState(GaussFabricatorBuiState state)
    {
        _received = state.ReceivedPower;
        ReceivedLabel.Text = FormatPower(state.ReceivedPower);
        OutputRateLabel.Text = _loc.GetString(
            "gauss-fabricator-window-output-rate",
            ("rate", state.OutputRate.ToString("F2")));

        _targetProgress = Math.Clamp(state.Progress, 0f, 1f);

        TemperatureBar.SetCurrent(state.Temperature);
        PressureBar.SetCurrent(state.Pressure);

        UpdateDrawLevel();
    }

    private void UpdateDrawLevel()
    {
        DrawLevelBar.Clear();
        DrawLevelBar.SetEntry("received", _received, ReceivedColor);
        DrawLevelBar.SetEntry("gap", Math.Max(0f, _drawRate - _received), DrawGapColor);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // It only goes backwards when it resets, so we dont want to lerp backwards.
        _displayedProgress = _targetProgress < _displayedProgress
            ? _targetProgress
            : MathHelper.Lerp(_displayedProgress, _targetProgress, MathHelper.Clamp01(8f * args.DeltaSeconds));

        _progressStyle.BackgroundColor = ProgressColor(_displayedProgress);
        OutputProgressBar.Value = _displayedProgress;
    }

    private void PopulateButtons()
    {
        AdjustmentButtons.Children.Clear();

        foreach (var increment in _increments)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            row.AddChild(BuildButton(-increment, "OpenRight"));
            row.AddChild(BuildButton(increment, "OpenLeft"));
            AdjustmentButtons.AddChild(row);
        }
    }

    private Button BuildButton(float delta, string styleClass)
    {
        // Formatted as kW in the locale string because POWERWATTS shows 1 kW as 1000 W
        var button = new Button
        {
            Text = _loc.GetString(
                delta < 0 ? "gauss-fabricator-window-adjust-decrease" : "gauss-fabricator-window-adjust-increase",
                ("value", Math.Abs(delta) / 1000f)),
            HorizontalExpand = true,
        };

        button.StyleClasses.Add(styleClass);
        button.OnPressed += _ => OnAdjustDrawRate?.Invoke(delta);
        return button;
    }

    private static Color ProgressColor(float t)
    {
        return t < 0.5f
            ? Color.InterpolateBetween(Color.Red, Color.Lime, t * 2f)
            : Color.InterpolateBetween(Color.Lime, Color.Cyan, (t - 0.5f) * 2f);
    }

    private string FormatPower(float value)
    {
        return _loc.GetString("battery-menu-power-value", ("value", value));
    }
}
