using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Silicons.LawProgrammer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Silicons.LawProgrammer;

[GenerateTypedNameReferences]
public sealed partial class LawProgrammerWindow : FancyWindow
{
    public LawProgrammerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(LawProgrammerBuiState state)
    {
        // todo : show the name of the lawset

        LawDisplayContainer.RemoveAllChildren();

        if (state.Laws == null || state.Laws.Count == 0)
        {
            LawsetNamePanel.Text = Loc.GetString("law-configurator-ui-absent-lawset-label");
            LockScreen.Visible = true;
            LawDisplayContainer.Visible = false;
            return;
        }


        LawsetNamePanel.Text = state.Name;

        LockScreen.Visible = false;
        LawDisplayContainer.Visible = true;

        state.Laws.Sort();
        foreach (var law in state.Laws)
        {
            LawDisplayContainer.AddChild(new LawProgrammerLawDisplay(law));
        }
    }
}
