using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Librarian;

[GenerateTypedNameReferences]
public sealed partial class LibraryBookEntry : Control
{
    public LibraryBookEntry()
    {
        RobustXamlLoader.Load(this);
    }

    public LibraryBookEntry(string title, string author)
    {
        RobustXamlLoader.Load(this);

        EntryTitle.Text = title;
        EntryAuthor.Text = author;
    }
}

