using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Librarian;

[GenerateTypedNameReferences]
public sealed partial class LibraryUploadWindow : Control
{
    public LibraryUploadWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

