using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Librarian;

[GenerateTypedNameReferences]
public sealed partial class LibraryConsoleMenu : FancyWindow
{
    public LibraryConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        ShowUploadWindow();
        RepoButton.OnPressed += _ => ShowRepoWindow();
        UploadButton.OnPressed += _ => ShowUploadWindow();
    }

    private void ShowRepoWindow()
    {
        RepositoryWindow.Visible = true;
        UploadWindow.Visible = false;
    }

    private void ShowUploadWindow()
    {
        RepositoryWindow.Visible = false;
        UploadWindow.Visible = true;
    }
}

