using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Librarian;

[GenerateTypedNameReferences]
public sealed partial class LibraryRepositoryWindow : Control
{
    public LibraryRepositoryWindow()
    {
        RobustXamlLoader.Load(this);

        LoadRepoBooks();
    }

    private void LoadRepoBooks()
    {
        for (var i = 0; i < 10; i++)
        {
            BookList.AddChild(new LibraryBookEntry("Title" + i, "Author"));
        }
    }

}

