using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Ghost.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

// AXOLOTL: Imports for ghostrespawn
using Robust.Shared.Timing;
using Robust.Shared.Configuration;
using Content.Shared.CCVar;
using Content.Client._AXOLOTL.RespawnButton;
using Content.Shared._Moffstation.CCVars;
using Robust.Client.Player;
using Robust.Shared.Player;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    public GhostTargetWindow TargetWindow { get; }

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    private int _prevNumberRoles;

    // AXOLOTL: Respawn button
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IConfigurationManager _configurationManager = default!;
    [Dependency] private readonly ISharedPlayerManager _playerManager = default!;

    private TimeSpan? _axolotlTimeOfDeath;
    private float _axolotlMinTimeToRespawn;
    public GhostRespawnRulesWindow AxolotlGhostRespawnRulesWindow { get; }
    public event Action? AxolotlGhostRespawnPressed;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindow();

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleBase.ButtonCaution);

        // AXOLOTL: Ghostrespawn
        AxolotlGhostRespawnRulesWindow = new GhostRespawnRulesWindow();
        AxolotlGhostRespawnRulesWindow.RespawnButton.OnPressed += _ => AxolotlGhostRespawnPressed?.Invoke();
        AxolotlGhostRespawnButton.OnPressed += _ => AxolotlGhostRespawnRulesWindow.OpenCentered();
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    // AXOLOTL: Set time of death info
    public void Update(int? roles, bool? canReturnToBody, TimeSpan? timeOfDeath, float minTimeToRespawn)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        _axolotlTimeOfDeath = timeOfDeath;
        _axolotlMinTimeToRespawn = minTimeToRespawn;

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleBase.ButtonCaution);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }

    // AXOLOTL: Required to make the ghost respawn timer tick
    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_axolotlTimeOfDeath is null)
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-denied", ("time", "unknown"));
            AxolotlGhostRespawnButton.Disabled = true;
            return;
        }

        if (_configurationManager.GetCVar(MoffCCVars.RespawnTime) == 0.0)
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("axolotl-respawn-disabled-always");
            AxolotlGhostRespawnButton.Disabled = true;
            return;
        }

        if (_playerManager.PlayerCount > _configurationManager.GetCVar(MoffCCVars.MaxPlayersForRespawnButton))
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("axolotl-respawn-disabled-players");
            AxolotlGhostRespawnButton.Disabled = true;
            return;
        }

        var delta = (_axolotlMinTimeToRespawn - _gameTiming.CurTime.Subtract(_axolotlTimeOfDeath.Value).TotalSeconds);
        if (delta <= 0)
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-allowed");
            AxolotlGhostRespawnButton.Disabled = false;
        }
        else
        {
            AxolotlGhostRespawnButton.Text = Loc.GetString("ghost-gui-respawn-button-denied", ("time", $"{delta:f1}"));
            AxolotlGhostRespawnButton.Disabled = true;
        }
    }

    public void AxolotlUpdateRespawn(TimeSpan? todd)
    {
        if (todd != null)
        {
            _axolotlTimeOfDeath = todd;
            _axolotlMinTimeToRespawn = _configurationManager.GetCVar(MoffCCVars.RespawnTime);
        }
    }
}
