using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Antags.UI;

[GenerateTypedNameReferences]
public sealed partial class AntagEntry : PanelContainer
{
    [Dependency] private JobRequirementsManager _requirements = default!;
    [Dependency] private IClientPreferencesManager _preferencesManager = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected => AntagCheckbox.Pressed;

    private readonly AntagPrototype _antag;

    public AntagEntry(AntagPrototype antag, bool enabled)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _antag = antag;

        // Enable mouse events so tooltips work
        MouseFilter = MouseFilterMode.Pass;

        AntagNameLabel.Text = Loc.GetString(antag.Name);
        AntagDescriptionLabel.Text = Loc.GetString(antag.Objective);

        AntagCheckbox.Pressed = enabled;
        AntagCheckbox.OnToggled += OnCheckboxToggled;

        SetupRequirements();
    }

    private void SetupRequirements()
    {
        if (!_requirements.IsAllowed(_antag,
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                out var reason))
        {
            AntagCheckbox.Pressed = false;
            AntagCheckbox.Disabled = true;
            OnToggled?.Invoke(IsSelected);
        }
    }

    private void OnCheckboxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        OnToggled?.Invoke(args.Pressed);
    }
}
