using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.DiegeticUI;

[GenerateTypedNameReferences]
public sealed partial class MoffDiegeticButton : ContainerButton
{
    private const float NativeSize = 32f;
    private const float DisplayScale = 1.5f;
    private const float PressedDarken = 0.7f;

    public event Action? OnKeyPressed;

    [Dependency] private IResourceCache _resourceCache = null!;

    private Color _baseColor = Color.White;
    private Color _hoverColor = new(1.2f, 1.2f, 1.2f);
    private Color _pressedColor = new(PressedDarken, PressedDarken, PressedDarken);
    private readonly VectorFont _fontOverride;
    private readonly bool _controlsReady;

    [ViewVariables]
    public string? Text
    {
        get => KeyLabel.Text;
        set
        {
            KeyLabel.Text = value;
            CenterLabel();
        }
    }

    [ViewVariables]
    public Color Color
    {
        get => _baseColor;
        set => SetTint(value);
    }

    [ViewVariables]
    public Color FontColor
    {
        set => KeyLabel.FontColorOverride = value;
    }

    public MoffDiegeticButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _controlsReady = true;

        _fontOverride ??= new VectorFont(_resourceCache.GetResource<FontResource>("/Fonts/Sysfont/Sysfont-Regular.otf"), 14);
        KeyLabel.FontOverride = _fontOverride;

        var displaySize = NativeSize * DisplayScale;
        SetSize = new Vector2(displaySize, displaySize);

        KeySprite.SetSize = new Vector2(displaySize, displaySize);
        LayoutContainer.SetPosition(KeySprite, Vector2.Zero);

        CenterLabel();

        OnPressed += _ => OnKeyPressed?.Invoke();

        DrawModeChanged();
    }

    // Re-centres the label for its current text; the perspective lift nudges it up
    // slightly so it sits on the key's top face. Must run whenever Text changes,
    // since the measured text size drives the position.
    private void CenterLabel()
    {
        var displaySize = NativeSize * DisplayScale;
        const float perspectiveLift = 4f;

        KeyLabel.Measure(Vector2Helpers.Infinity);
        var labelSize = KeyLabel.DesiredSize;
        var labelPos = new Vector2(
            (displaySize - labelSize.X) / 2f,
            (displaySize - labelSize.Y) / 2f - perspectiveLift);
        LayoutContainer.SetPosition(KeyLabel, labelPos);
    }

    private void SetTint(Color color)
    {
        _baseColor = color;
        const float hoverMultiplier = 1.1f;
        const float pressedMultiplier = 0.7f;
        _hoverColor = new Color(color.R * hoverMultiplier, color.G * hoverMultiplier, color.B * hoverMultiplier);
        _pressedColor = new Color(color.R * pressedMultiplier, color.G * pressedMultiplier, color.B * pressedMultiplier);
        DrawModeChanged();
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();

        // ContainerButton's constructor calls this before RobustXamlLoader.Load has
        // wired up the named controls; touching KeySprite before then throws in
        // FindControl, so bail until the XAML tree exists.
        if (!_controlsReady)
            return;

        KeySprite.Modulate = DrawMode switch
        {
            DrawModeEnum.Pressed => _pressedColor,
            DrawModeEnum.Hover => _hoverColor,
            _ => _baseColor,
        };
    }
}
