- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  joinNotifyCrew: true
  joinNotifyCrewText: prisoner-arrivals-notice
  joinNotifyCrewColor: orange
  access:
  - GenpopEnter

- type: startingGear
  id: PrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    id: PrisonerIDCardPerma
    ears: ClothingHeadsetGrey
