using System.Linq;
using Content.Shared._Moffstation.Atmos.Components;
using Content.Shared._Moffstation.Atmos.EntitySystems;
using Content.Shared._Moffstation.Atmos.Visuals;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.SprayPainter.UI;

[GenerateTypedNameReferences]
public sealed partial class GasTankPainterWindow : Control
{
    private event Action<GasHolderVisuals>? OnVisualsPicked;

    [Dependency] private IEntitySystemManager _sysMan = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    private readonly GasHolderVisualsSystem _gasHolderVisuals;

    private static readonly EntProtoId<GasTankVisualsComponent> TankDummyProto = "OxygenTank";
    private static readonly EntProtoId<GasCanVisualsComponent> CanDummyProto = "OxygenCanister";

    private readonly Dictionary<GasHolderVisualStylePrototype, int> _stylesToListIndeces = new();

    private bool _suppressSelectingStyleCallback = false;
    private bool _suppressChangingColorsCallbackAndPreviewUpdate = false;

    /// <summary>
    /// This generic function is used as the callback for all of the color sliders and "use this stripe" checkboxes.
    /// </summary>
    private void OnColorsChanged<T>(T unused)
    {
        if (_suppressChangingColorsCallbackAndPreviewUpdate)
            return;

        // Deselect any predefined styles if we're changing color values directly.
        StyleList.ClearSelected();

        var colors = new GasTankColorValues(
            TankColor.Color,
            UseMiddleStripe.Pressed ? MiddleStripeColor.Color : null,
            UseLowerStripe.Pressed ? LowerStripeColor.Color : null
        );
        OnVisualsPicked?.Invoke(colors);
        UpdatePreview(colors);
    }

    /// <param name="onVisualsPicked">The behavior to invoke when the configured visuals are changed.</param>
    public GasTankPainterWindow(Action<GasHolderVisuals>? onVisualsPicked)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _gasHolderVisuals = _sysMan.GetEntitySystem<GasHolderVisualsSystem>();

        OnVisualsPicked = onVisualsPicked;

        // Initialize the preview dummy entity.
        TankPreview.SetEntity(_entMan.Spawn(TankDummyProto));
        CanPreview.SetEntity(_entMan.Spawn(CanDummyProto));

        // Initialize the list of style prototypes.
        var sortedStyles = _proto.EnumeratePrototypes<GasHolderVisualStylePrototype>()
            .Select(style => (_loc.GetString(style.Name), style))
            .OrderBy(it => it.Item1);
        foreach (var (index, (localizedName, style)) in sortedStyles.Index())
        {
            StyleList.AddItem(localizedName, metadata: style);
            _stylesToListIndeces.Add(style, index);
        }

        // Selecting a style sets the color slider values (without those invoking the "we have changed the
        // configuration" or the "update the preview" callbacks), updates the preview's visuals, and invokes the "we
        // have changed the configuration" callback.
        StyleList.OnItemSelected += args =>
        {
            var style = (GasHolderVisualStylePrototype)args.ItemList[args.ItemIndex].Metadata!;
            SetColorSliderValues(style.ColorValues);
            UpdatePreview(style.ColorValues);
            if (!_suppressSelectingStyleCallback)
                OnVisualsPicked?.Invoke(style);
        };

        // Changing the color sliders or checkboxes invokes the "we have changed the configuration" callback and updates
        // the preview.
        TankColor.OnColorChanged += OnColorsChanged;
        MiddleStripeColor.OnColorChanged += OnColorsChanged;
        LowerStripeColor.OnColorChanged += OnColorsChanged;
        UseMiddleStripe.OnToggled += OnColorsChanged;
        UseLowerStripe.OnToggled += OnColorsChanged;
    }

    private void UpdatePreview(GasTankColorValues colorValues)
    {
        if (TankPreview.Entity is { } tank)
        {
            _gasHolderVisuals.TrySetTankVisuals<GasTankVisualsComponent>(tank.Owner, colorValues);
        }

        if (CanPreview.Entity is { } can)
        {
            _gasHolderVisuals.TrySetTankVisuals<GasCanVisualsComponent>(can.Owner, colorValues);
        }
    }

    public void SetVisuals(GasHolderVisuals visuals)
    {
        switch (visuals)
        {
            case GasHolderVisuals.GasHolderVisualsPrototype p when _proto.TryIndex(p.Prototype, out var prototype):
            {
                SetSelectedStyle(prototype);
                break;
            }
            case GasHolderVisuals.GasHolderVisualsColorValues v:
                SetColorSliderValues(v.Values);
                break;
        }
    }

    private void SetSelectedStyle(GasHolderVisualStylePrototype style)
    {
        if (!_stylesToListIndeces.TryGetValue(style, out var index))
            return;

        // Suppress the callback which might eventually cause re-entrance to this function.
        _suppressSelectingStyleCallback = true;
        StyleList[index].Selected = true;
        _suppressSelectingStyleCallback = false;
    }

    private void SetColorSliderValues(GasTankColorValues colorValues)
    {
        // If we're setting the colors manually, don't send the callback which might eventually cause re-entrance to
        // this function.
        _suppressChangingColorsCallbackAndPreviewUpdate = true;

        TankColor.Color = colorValues.TankColor;
        MiddleStripeColor.Color = colorValues.MiddleStripeColor ?? Color.White;
        UseMiddleStripe.Pressed = colorValues.MiddleStripeColor != null;
        LowerStripeColor.Color = colorValues.LowerStripeColor ?? Color.White;
        UseLowerStripe.Pressed = colorValues.LowerStripeColor != null;

        _suppressChangingColorsCallbackAndPreviewUpdate = false;
    }
}
