using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.AdminGhost;
using Content.Shared.Overlays;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Console;

namespace Content.Client._Moffstation.AdminGhost;

[GenerateTypedNameReferences]
public sealed partial class AdminGhostWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IConsoleHost _console = default!;

    private EntityUid _ghostEntity;
    private bool _initialized;

    public AdminGhostWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BrowseSpriteButton.OnPressed += _ => OnBrowseSprite();
        SetSpriteButton.OnPressed += _ => OnSetSprite();
        ClearSpriteButton.OnPressed += _ => OnClearSprite();
        SetNameButton.OnPressed += _ => OnSetName();
        SetDescriptionButton.OnPressed += _ => OnSetDescription();
        SetMapTextButton.OnPressed += _ => OnSetMapText();
        ClearMapTextButton.OnPressed += _ => OnClearMapText();
        SetWalkSpeedButton.OnPressed += _ => OnSetWalkSpeed();
        SetSprintSpeedButton.OnPressed += _ => OnSetSprintSpeed();
        ToggleJobIconsButton.OnPressed += _ => OnToggleOverlay("jobicons", ToggleJobIconsButton);
        ToggleCriminalButton.OnPressed += _ => OnToggleOverlay("criminal", ToggleCriminalButton);
        ToggleMindshieldButton.OnPressed += _ => OnToggleOverlay("mindshield", ToggleMindshieldButton);
        ToggleSyndicateButton.OnPressed += _ => OnToggleOverlay("syndicate", ToggleSyndicateButton);
        ToggleHealthBarsButton.OnPressed += _ => OnToggleOverlay("healthbars", ToggleHealthBarsButton);
        SaveButton.OnPressed += _ => OnSave();
        LoadButton.OnPressed += _ => OnLoad();
        ResetAllButton.OnPressed += _ => OnResetAll();
    }

    public void Initialize(EntityUid ghostEntity)
    {
        _ghostEntity = ghostEntity;
        _initialized = true;
        Refresh();
    }

    public void Refresh()
    {
        if (!_initialized)
            return;

        if (_entMan.TryGetComponent(_ghostEntity, out AdminGhostCustomizationComponent? comp))
        {
            SpriteLineEdit.Text = comp.SpritePrototype ?? "";
            NameLineEdit.Text = comp.CustomName ?? "";
            DescriptionLineEdit.Text = comp.CustomDescription ?? "";
            MapTextLineEdit.Text = comp.MapText?.Text ?? "";
            MapTextColorSelector.Color = comp.MapText?.Color ?? Color.White;
            MapTextOffsetXLineEdit.Text = comp.MapText?.Offset.X.ToString("F1") ?? "";
            MapTextOffsetYLineEdit.Text = comp.MapText?.Offset.Y.ToString("F1") ?? "";
            WalkSpeedLineEdit.Text = comp.WalkSpeed?.ToString("F1") ?? "";
            SprintSpeedLineEdit.Text = comp.SprintSpeed?.ToString("F1") ?? "";
        }
        else
        {
            SpriteLineEdit.Text = "";
            NameLineEdit.Text = "";
            DescriptionLineEdit.Text = "";
            MapTextLineEdit.Text = "";
            MapTextColorSelector.Color = Color.White;
            MapTextOffsetXLineEdit.Text = "";
            MapTextOffsetYLineEdit.Text = "";
            WalkSpeedLineEdit.Text = "";
            SprintSpeedLineEdit.Text = "";
        }

        UpdateOverlayButton(ToggleJobIconsButton, "Job Icons", _entMan.HasComponent<ShowJobIconsComponent>(_ghostEntity));
        UpdateOverlayButton(ToggleCriminalButton, "Criminal Records", _entMan.HasComponent<ShowCriminalRecordIconsComponent>(_ghostEntity));
        UpdateOverlayButton(ToggleMindshieldButton, "Mindshield", _entMan.HasComponent<ShowMindShieldIconsComponent>(_ghostEntity));
        UpdateOverlayButton(ToggleSyndicateButton, "Syndicate", _entMan.HasComponent<ShowSyndicateIconsComponent>(_ghostEntity));
        UpdateOverlayButton(ToggleHealthBarsButton, "Health Bars", _entMan.HasComponent<ShowHealthBarsComponent>(_ghostEntity));
    }

    private static void UpdateOverlayButton(Button button, string label, bool enabled)
    {
        button.Text = $"{label}: {(enabled ? "On" : "Off")}";
        button.ModulateSelfOverride = enabled ? Color.LimeGreen : null;
    }

    private void OnBrowseSprite()
    {
        var browser = new PrototypeBrowserWindow();
        browser.OnPrototypeSelected += proto =>
        {
            SpriteLineEdit.Text = proto;
            _console.ExecuteCommand($"ghostcustom sprite {proto}");
        };
        browser.OpenCentered();
    }

    private void OnSetSprite()
    {
        var proto = SpriteLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(proto))
            return;
        _console.ExecuteCommand($"ghostcustom sprite {proto}");
    }

    private void OnClearSprite()
    {
        SpriteLineEdit.Text = "";
        _console.ExecuteCommand("ghostcustom sprite clear");
    }

    private void OnSetName()
    {
        var name = NameLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(name))
            return;
        _console.ExecuteCommand($"ghostcustom name {name}");
    }

    private void OnSetDescription()
    {
        var desc = DescriptionLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(desc))
            return;
        _console.ExecuteCommand($"ghostcustom desc {desc}");
    }

    private void OnSetMapText()
    {
        var text = MapTextLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;

        var color = MapTextColorSelector.Color;
        var offsetX = MapTextOffsetXLineEdit.Text.Trim();
        var offsetY = MapTextOffsetYLineEdit.Text.Trim();

        var cmd = $"ghostcustom maptext {text} --color {color.ToHex()}";
        if (!string.IsNullOrEmpty(offsetX))
            cmd += $" --offset-x {offsetX}";
        if (!string.IsNullOrEmpty(offsetY))
            cmd += $" --offset-y {offsetY}";

        _console.ExecuteCommand(cmd);
    }

    private void OnClearMapText()
    {
        MapTextLineEdit.Text = "";
        MapTextOffsetXLineEdit.Text = "";
        MapTextOffsetYLineEdit.Text = "";
        _console.ExecuteCommand("ghostcustom maptext clear");
    }

    private void OnSetWalkSpeed()
    {
        var text = WalkSpeedLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;
        _console.ExecuteCommand($"ghostcustom speed {text} {SprintSpeedLineEdit.Text.Trim()}");
    }

    private void OnSetSprintSpeed()
    {
        var text = SprintSpeedLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;
        _console.ExecuteCommand($"ghostcustom speed {WalkSpeedLineEdit.Text.Trim()} {text}");
    }

    private void OnToggleOverlay(string name, Button button)
    {
        var currentlyOn = button.ModulateSelfOverride == Color.LimeGreen;
        UpdateOverlayButton(button, GetOverlayLabel(name), !currentlyOn);

        _console.ExecuteCommand($"ghostcustom overlay {name}");
    }

    private static string GetOverlayLabel(string name)
    {
        return name switch
        {
            "jobicons" => "Job Icons",
            "criminal" => "Criminal Records",
            "mindshield" => "Mindshield",
            "syndicate" => "Syndicate",
            "healthbars" => "Health Bars",
            _ => name
        };
    }

    private void OnSave()
    {
        _console.ExecuteCommand("ghostcustom save");
    }

    private void OnLoad()
    {
        _console.ExecuteCommand("ghostcustom load");
    }

    private void OnResetAll()
    {
        _console.ExecuteCommand("ghostcustom reset");
        Close();
    }
}
