using System.Linq;
using System.Numerics;
using Content.Client._Moffstation.Preferences;
using Content.Client.Lobby.UI.Roles;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Lobby.UI;

/// <summary>
/// Editor for job priorities, which apply across all of the player's characters. Which jobs a
/// character will take is chosen per character in the roles tab. Adapted from upstream PR #36493.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MoffJobPriorityWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private JobRequirementsManager _requirements = default!;
    [Dependency] private MoffCharacterSelectionManager _selection = default!;

    private readonly SpriteSystem _sprite;

    // A job can appear in several departments, so entries are not unique by job id.
    private readonly List<(ProtoId<JobPrototype> Job, RequirementsSelector Selector)> _selectors = new();

    private readonly Dictionary<string, BoxContainer> _departments = new();

    public MoffJobPriorityWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();

        Refresh();

        _selection.OnStateChanged += UpdateSelectors;
    }

    public void Refresh()
    {
        JobList.RemoveAllChildren();
        _departments.Clear();
        _selectors.Clear();

        // RadioOptions ids are auto-incremented; these only work because they match JobPriority 0-3.
        var items = new[]
        {
            ("humanoid-profile-editor-job-priority-never-button", (int)JobPriority.Never),
            ("humanoid-profile-editor-job-priority-low-button", (int)JobPriority.Low),
            ("humanoid-profile-editor-job-priority-medium-button", (int)JobPriority.Medium),
            ("humanoid-profile-editor-job-priority-high-button", (int)JobPriority.High),
        };

        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .ToList();

        departments.Sort(DepartmentUIComparer.Instance);

        var first = true;

        foreach (var department in departments)
        {
            var category = GetOrCreateCategory(department, ref first);

            var jobs = department.Roles
                .Select(jobId => _prototypeManager.Index(jobId))
                .Where(job => job.SetPreference)
                .ToList();

            jobs.Sort(JobUIComparer.Instance);

            foreach (var job in jobs)
            {
                category.AddChild(CreateSelector(job, items));
            }
        }

        UpdateSelectors();
    }

    private BoxContainer GetOrCreateCategory(DepartmentPrototype department, ref bool first)
    {
        if (_departments.TryGetValue(department.ID, out var existing))
            return existing;

        var category = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Name = department.ID,
            HorizontalExpand = true,
        };

        if (first)
            first = false;
        else
            category.AddChild(new Control { MinSize = new Vector2(0, 23) });

        category.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = department.Color },
            Children =
            {
                new RichTextLabel
                {
                    Text = Loc.GetString(
                        "humanoid-profile-editor-department-jobs-label-moffstation",
                        ("departmentName", Loc.GetString(department.Name))),
                    Margin = new Thickness(5f, 2f, 0, 2f),
                },
            },
        });

        _departments[department.ID] = category;
        JobList.AddChild(category);

        return category;
    }

    private RequirementsSelector CreateSelector(JobPrototype job, (string, int)[] items)
    {
        var selector = new RequirementsSelector
        {
            Margin = new Thickness(3f, 3f, 3f, 0f),
        };

        var icon = new TextureRect
        {
            TextureScale = new Vector2(2, 2),
            VerticalAlignment = Control.VAlignment.Center,
        };

        var jobIcon = _prototypeManager.Index(job.Icon);
        icon.Texture = _sprite.Frame0(jobIcon.Icon);

        selector.Setup(items, job.LocalizedName, 200, job.LocalizedDescription, icon, job.Guides);

        // Player-global, so there is no character to check age or species against.
        if (!_requirements.IsAllowed(job, null, out var reason))
            selector.LockRequirements(reason);
        else
            selector.UnlockRequirements();

        selector.OnSelected += selected => OnJobSelected(job.ID, (JobPriority)selected);

        _selectors.Add((job.ID, selector));

        return selector;
    }

    private void OnJobSelected(ProtoId<JobPrototype> job, JobPriority priority)
    {
        var priorities = new Dictionary<ProtoId<JobPrototype>, JobPriority>(_selection.State.JobPriorities)
        {
            [job] = priority,
        };

        // Only one high priority job is allowed.
        if (priority == JobPriority.High)
        {
            foreach (var (other, otherPriority) in _selection.State.JobPriorities)
            {
                if (other != job && otherPriority == JobPriority.High)
                    priorities[other] = JobPriority.Medium;
            }
        }

        _selection.UpdateJobPriorities(priorities);
    }

    /// <summary>Keeps duplicated jobs and demoted high-priority jobs in sync.</summary>
    private void UpdateSelectors()
    {
        foreach (var (job, selector) in _selectors)
        {
            selector.Select((int)_selection.GetPriority(job));
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _selection.OnStateChanged -= UpdateSelectors;
    }
}
