using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CrewManifest.UI;

[GenerateTypedNameReferences]
public sealed partial class CrewManifestEntryControl : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    public const string GenderStyleClass = "CrewManifestGender";

    public CrewManifestEntryControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public CrewManifestEntryControl(Content.Shared.CrewManifest.CrewManifestEntry entry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NameLabel.SetMessage(entry.Name);
        GenderLabel.SetMessage(Loc.GetString("gender-display", ("gender", entry.Gender)), Color.Gray);
        TitleLabel.SetMessage(entry.JobTitle);

        if (_prototypeManager.TryIndex<JobIconPrototype>(entry.JobIcon, out var jobIcon))
        {
            JobIcon.Texture = _entityManager.System<SpriteSystem>().Frame0(jobIcon.Icon);
            JobIcon.Visible = true;
        }
    }
}
