using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Body.Components;
using Content.Shared._Moffstation.Medical.CryoCapsule;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Components;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.Medical.CryoCapsule;

[GenerateTypedNameReferences]
public sealed partial class CryoLifeSupportWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly SharedAtmosphereSystem _atmosphere = default!;

    public Action? OnEjectBeakerPressed;
    public Action? OnDetachCapsulePressed;
    public Action? OnJumpStartBrainPressed;
    public Action<int>? OnInjectPressed;

    public CryoLifeSupportWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _atmosphere = _entityManager.System<SharedAtmosphereSystem>();

        JumpStartBrainButton.OnPressed += _ => OnJumpStartBrainPressed?.Invoke();
        DetachCapsuleButton.OnPressed += _ => OnDetachCapsulePressed?.Invoke();

        EjectBeakerButton.OnPressed += _ => OnEjectBeakerPressed?.Invoke();
        Inject1.OnPressed += _ => OnInjectPressed?.Invoke(1);
        Inject5.OnPressed += _ => OnInjectPressed?.Invoke(5);
        Inject10.OnPressed += _ => OnInjectPressed?.Invoke(10);
        Inject20.OnPressed += _ => OnInjectPressed?.Invoke(20);
    }


    public void SetState(CryoLifeSupportUiState state)
    {
        SetGasMix(state.GasMix);
        SetBeakerMix(state);
        SetCapsule(state.CapsuleEntity, state.Organs);
    }

    private void SetCapsule(NetEntity? capsule, List<(string,OrganEntry)>? organs)
    {
        if (capsule is not { } entity)
        {
            PatientSection.Visible = false;
            return;
        }

        PatientSection.Visible = true;
        SpriteView.SetEntity(entity);

        NameLabel.Text = "CryoCapsule";
        SpeciesLabel.Text = "Ready"; // todo !

        OrgansCheckList.RemoveAllChildren();

        if (organs is null)
            return;

        foreach (var (name, entry) in organs)
        {
            OrgansCheckList.AddChild(new OrganStatusControl(name, entry));
        }
    }

    private void SetGasMix(GasMixEntry mix)
    {
        Pressure.Text = Loc.GetString("gas-analyzer-window-pressure-val-text",
            ("pressure", $"{mix.Pressure:0.00}"));
        Temperature.Text = Loc.GetString("generic-not-available-shorthand");

        GasMixChart.Clear();
        if (mix.Pressure < Atmospherics.GasMinMoles ||
            mix.Gases == null)
        {
            GasMixChart.Visible = false;
            return;
        }

        GasMixChart.Visible = true;

        var celsius = TemperatureHelpers.KelvinToCelsius(mix.Temperature);
        Temperature.Text = Loc.GetString("gas-analyzer-window-temperature-val-text",
            ("tempK", $"{mix.Temperature:0.0}"),
            ("tempC", $"{celsius:0.0}"));

        var totalGasAmount = mix.Gases.Sum(gas => gas.Amount);

        foreach (var gasEntry in mix.Gases)
        {
            var gasProto = _atmosphere.GetGas(gasEntry.Gas);
            var percent = gasEntry.Amount / totalGasAmount * 100;
            var localizedName = Loc.GetString(gasProto.Name);
            var tooltip = Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                ("gasName", localizedName),
                ("amount", $"{gasEntry.Amount:0.##}"),
                ("percentage", $"{percent:0.#}"));
            GasMixChart.AddEntry(gasEntry.Amount, gasProto.Color, tooltip: tooltip);
        }
    }

    private void SetBeakerMix(CryoLifeSupportUiState state)
    {
        var totalBeakerCapacity = state.ReagentsCapacity ?? 0;
        var availableQuantity = new FixedPoint2();

        ChemicalsChart.Clear();
        ChemicalsChart.Capacity = (totalBeakerCapacity < 1 ? 50 : (int)totalBeakerCapacity);

        var chartMaxChemsQuantity = ChemicalsChart.Capacity;

        if (state.Reagents != null)
        {
            foreach (var (reagent, quantity) in state.Reagents!)
            {
                availableQuantity += quantity;

                // Make sure we don't add too many chemicals to the chart, so that there's still enough space to
                // visualize the injection buffer.
                var chemsQuantityOvershoot = FixedPoint2.Max(0, availableQuantity - chartMaxChemsQuantity);
                var chartQuantity = FixedPoint2.Max(0, quantity - chemsQuantityOvershoot);

                var reagentProto = _prototypeManager.Index<ReagentPrototype>(reagent.Prototype);
                ChemicalsChart.SetEntry(
                    reagent.Prototype,
                    reagentProto.LocalizedName,
                    (float)chartQuantity,
                    reagentProto.SubstanceColor,
                    tooltip: $"{quantity}u {reagentProto.LocalizedName}"
                );
            }
        }

        var hasPatient = (state.CapsuleEntity != null);

        var isChemicalsChartVisible = (state.Reagents != null);
        NoBeakerText.Visible = !isChemicalsChartVisible;
        ChemicalsChart.Visible = isChemicalsChartVisible;
        Inject1.Disabled = (!hasPatient || availableQuantity < 0.1f);
        Inject5.Disabled = (!hasPatient || availableQuantity <= 1);
        Inject10.Disabled = (!hasPatient || availableQuantity <= 5);
        Inject20.Disabled = (!hasPatient || availableQuantity <= 10);
        EjectBeakerButton.Disabled = state.Reagents == null;
    }
}
