using Content.Shared._Moffstation.Body.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Medical.CryoCapsule;

[GenerateTypedNameReferences]
public sealed partial class OrganStatusControl : GridContainer
{
    public OrganStatusControl(List<OrganEntry> status)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        foreach (var organ in status)
        {
            var statusString =
                organ.Status == OrganEntry.OrganStatus.Absent
                    ? Loc.GetString("cryomachine-window-organ-absent")
                    : Loc.GetString("cryomachine-window-organ-healthy");
            // todo : add specie and stuff
            // todo : add compatibility warning

            AddChild(new Label()
            {
                Text = organ.Name + ':',
                StyleClasses = { "LabelSubText" },
            });
            AddChild(new RichTextLabel()
            {
                Text = statusString,
            });
        }
    }
}
