using Content.Shared._Moffstation.Body.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Medical.CryoCapsule;

[GenerateTypedNameReferences]
public sealed partial class OrganStatusControl : GridContainer
{
    public OrganStatusControl(string name, OrganEntry entry)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        string statusString;
        switch (entry.Status)
        {
            case OrganEntry.OrganStatus.Absent:
                statusString = Loc.GetString("cryomachine-window-organ-absent");
                break;
            case OrganEntry.OrganStatus.Unusable:
                statusString = Loc.GetString("cryomachine-window-organ-unusable");
                break;
            case OrganEntry.OrganStatus.Damaged:
                statusString = Loc.GetString("cryomachine-window-organ-damaged");
                break;
            case OrganEntry.OrganStatus.Healthy:
                statusString = Loc.GetString("cryomachine-window-organ-healthy");
                break;
            default:
                statusString = Loc.GetString("cryomachine-window-organ-unknown");
                break;
        }

        AddChild(new Label
        {
            Text = name + ':',
            StyleClasses = { "LabelSubText" },
        });
        AddChild(new RichTextLabel
        {
            Text = statusString,
        });
        AddChild(new Label());
        AddChild(new Label
        {
            Text = Loc.GetString(entry.Specie),
            StyleClasses = { "LabelSubText" },
        });
    }
}
