# SPDX-FileCopyrightText: 2023 Vordenburg <114301317+Vordenburg@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 eclips_e <67359748+Just-a-Unity-Dev@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Plykiya <58439124+Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Ghagliiarghii <68826635+Ghagliiarghii@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025-2026 āda <ss.adasts@gmail.com>
# SPDX-License-Identifier: MIT

- type: entity
  abstract: true
  parent: BaseItem
  id: BaseBoardEntity # Board item
  name: board
  description: A blank board.
  components:
  - type: TabletopGame
    size: 256, 256
    setup:
      !type:TabletopEmptySetup
      boardPrototype: Crowbar
  - type: Tag
    tags:
    - TabletopBoard

- type: entity
  abstract: true
  parent: BaseItem
  id: BaseTabletopPiece # Board piece
  components:
  - type: TabletopDraggable
  - type: Sprite
    noRot: true
  - type: Appearance

# Entity which acts as the background sprite in the tabletop game
- type: entity
  abstract: true
  id: BaseBoardTabletop
  name: baseboard
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    noRot: false
    drawdepth: FloorTiles
