using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class ForgeSignatureWindow : DefaultWindow
{

    public event Action<string>? OnSignatureEntered;

	public ForgeSignatureWindow()
	{
        RobustXamlLoader.Load(this);

		SignatureLineEdit.OnTextEntered += e => OnSignatureEntered?.Invoke(e.Text);
	}


	public void SetCurrentSignature(string battlecry)
	{
		SignatureLineEdit.Text = battlecry;
	}

}


