using Content.Client.CartridgeLoader.Cartridges;
using Content.Client.UserInterface.Controls;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.LogProbe;

[GenerateTypedNameReferences]
public sealed partial class LogProbeWindow : FancyWindow
{
        /// <summary>
    /// Action invoked when the print button gets pressed.
    /// </summary>
    public Action? OnPrintPressed;

    public LogProbeWindow()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void UpdateState(LogProbeUiState state)
    {
        EntityName.Text = state.EntityName;
        PrintButton.Disabled = string.IsNullOrEmpty(state.EntityName);

        ProbedDeviceContainer.RemoveAllChildren();
        SetupAccessLogView();
        if (state.PulledLogs.Count > 0)
            DisplayAccessLogs(state.PulledLogs);
    }

    private void SetupAccessLogView()
    {
        TitleLabel.Text = Loc.GetString("log-probe-header-access");
        ContentLabel.Text = Loc.GetString("log-probe-label-accessor");
        CardNumberLabel.Visible = false;
    }

    private void DisplayAccessLogs(List<PulledAccessLog> logs)
    {
        //Reverse the list so the oldest entries appear at the bottom
        logs.Reverse();

        var count =  1;
        foreach (var log in logs)
        {
            AddAccessLog(log, count);
            count++;
        }
    }

    private void AddAccessLog(PulledAccessLog log, int numberLabelText)
    {
        var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
        var accessorLabelText = log.Accessor;
        var entry = new LogProbeUiEntry(numberLabelText, timeLabelText, accessorLabelText);

        ProbedDeviceContainer.AddChild(entry);
    }
}
