## Static

## Dynamic

- type: latheRecipePack
  id: MoffstationServiceBoards
  recipes:
  - UniformPrinterMachineCircuitboard
  - SheetifierMachineCircuitboard
  - CutterMachineCircuitboard
  - BiogeneratorMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - SmartFridgeCircuitboard
