- type: entity
  name: stun lance #As described by Buck himself
  parent: [BaseItem, BaseSecurityContraband]
  id: SpearStun
  description: An extended stun baton designed to prod clowns from a safe distance.
  components:
  - type: Sprite
    sprite: _Moffstation/Objects/Weapons/Melee/stunlance.rsi
    layers:
    - state: stunlance_off
      map: [ "enum.ToggleableVisuals.Layer" ]
  - type: Stunbaton
    energyPerUse: 50
  - type: ItemToggle
    predictable: false
    soundActivate:
      collection: sparks
      params:
        variation: 0.250
    soundDeactivate:
      collection: sparks
      params:
        variation: 0.250
    soundFailToActivate:
      path: /Audio/Machines/button.ogg
      params:
        variation: 0.250
  - type: ItemTogglePrefix
    prefixOn: on
    prefixOff: off
  - type: ItemToggleMeleeWeapon
    activatedDamage:
      types:
        Blunt: 0
  - type: MeleeWeapon
    wideAnimationRotation: -135
    damage:
      types:
        Blunt: 10
    bluntStaminaDamageFactor: 2.0
    angle: 0
    animation: WeaponArcThrust
    range: 2
  - type: StaminaDamageOnHit
    damage: 35
    sound: /Audio/Weapons/egloves.ogg
  - type: StaminaDamageOnCollide
    damage: 55 #Knocks the wind outta ya on throw, but you also lose your stick
    sound: /Audio/Weapons/egloves.ogg
  - type: ThrowingAngle
    angle: 225
  - type: LandAtCursor # it deals stamina damage when thrown
  - type: Battery
    maxCharge: 1000
    startingCharge: 1000
  - type: UseDelay
  - type: Item
    heldPrefix: off
    size: Ginormous
  - type: Clothing
    sprite: _Moffstation/Objects/Weapons/Melee/stunlance.rsi
    quickEquip: false
    slots:
    - back
    - suitStorage
  - type: DisarmMalus
    malus: 0.225
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.ToggleableVisuals.Enabled:
        enum.ToggleableVisuals.Layer:
          True: {state: stunlance_on}
          False: {state: stunlance_off}
  - type: StaticPrice
    price: 80
  - type: Riggable
  - type: SolutionContainerManager
    solutions:
      battery:
        maxVol: 5
  - type: InjectableSolution
    solution: battery
  - type: DrawableSolution
    solution: battery
  - type: Explosive
    explosionType: Default
    intensitySlope: 1.5
    maxIntensity: 200
  - type: PhysicalComposition
    materialComposition:
      Steel: 100
      Plastic: 100
  - type: GuideHelp
    guides:
    - Security
    - Antagonists
