using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Medical.AdvancedCryogenics;

[GenerateTypedNameReferences]
public sealed partial class CryomachineWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SharedAtmosphereSystem _atmosphere = default!;

    public Action? OnEjectBeakerPressed;
    public Action? OnJumpStartBrainPressed;
    public Action<int>? OnInjectPressed;

    public CryomachineWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _atmosphere = _entityManager.System<SharedAtmosphereSystem>();

        EjectPatientButton.OnPressed += _ => OnJumpStartBrainPressed?.Invoke(); // todo : change button name obviously
        EjectBeakerButton.OnPressed += _ => OnEjectBeakerPressed?.Invoke();
        Inject1.OnPressed += _ => OnInjectPressed?.Invoke(1);
        Inject5.OnPressed += _ => OnInjectPressed?.Invoke(5);
        Inject10.OnPressed += _ => OnInjectPressed?.Invoke(10);
        Inject20.OnPressed += _ => OnInjectPressed?.Invoke(20);
    }
}
