using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Medical.AdvancedCryogenics;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Components;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Medical.AdvancedCryogenics;

[GenerateTypedNameReferences]
public sealed partial class CryomachineWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SharedAtmosphereSystem _atmosphere = default!;

    public Action? OnEjectBeakerPressed;
    public Action? OnDetachCapsulePressed;
    public Action? OnJumpStartBrainPressed;
    public Action<int>? OnInjectPressed;

    public CryomachineWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _atmosphere = _entityManager.System<SharedAtmosphereSystem>();

        JumpStartBrainButton.OnPressed += _ => OnJumpStartBrainPressed?.Invoke();
        DetachCapsuleButton.OnPressed += _ => OnDetachCapsulePressed?.Invoke();

        EjectBeakerButton.OnPressed += _ => OnEjectBeakerPressed?.Invoke();
        Inject1.OnPressed += _ => OnInjectPressed?.Invoke(1);
        Inject5.OnPressed += _ => OnInjectPressed?.Invoke(5);
        Inject10.OnPressed += _ => OnInjectPressed?.Invoke(10);
        Inject20.OnPressed += _ => OnInjectPressed?.Invoke(20);
    }


    public void SetState(CryomachineUiState state)
    {
        SetGasMix(state.GasMix);
        SetCapsule(state.CryoCapsule, state.CapsuleNetEnt);
    }

    private void SetCapsule(CryoCapsuleEntry entry, NetEntity? capsule)
    {
        if (capsule is { } entity)
            CapsuleSprite.SetEntity(entity);
        JumpStartBrainButton.Disabled = !entry.BrainPresent;
    }

    private void SetGasMix(GasMixEntry mix)
    {
        bool hasGas = (mix.Pressure > Atmospherics.GasMinMoles);

        Pressure.Text = Loc.GetString("gas-analyzer-window-pressure-val-text",
            ("pressure", $"{mix.Pressure:0.00}"));
        Temperature.Text = Loc.GetString("generic-not-available-shorthand");

        if (hasGas)
        {
            var celsius = TemperatureHelpers.KelvinToCelsius(mix.Temperature);
            Temperature.Text = Loc.GetString("gas-analyzer-window-temperature-val-text",
                ("tempK", $"{mix.Temperature:0.0}"),
                ("tempC", $"{celsius:0.0}"));
        }


        GasMixChart.Clear();
        GasMixChart.Visible = hasGas;

        if (mix.Gases != null)
        {
            var totalGasAmount = mix.Gases.Sum(gas => gas.Amount);

            foreach (var gasEntry in mix.Gases)
            {
                var gasProto = _atmosphere.GetGas(gasEntry.Gas);
                var percent = gasEntry.Amount / totalGasAmount * 100;
                var localizedName = Loc.GetString(gasProto.Name);
                var tooltip = Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                    ("gasName", localizedName),
                    ("amount", $"{gasEntry.Amount:0.##}"),
                    ("percentage", $"{percent:0.#}"));
                GasMixChart.AddEntry(gasEntry.Amount, gasProto.Color, tooltip: tooltip);
            }
        }
    }

    private void SetBeakerMix()
    {
        // what will we inject in the dude.
    }
}
