using System.Numerics;
using Content.Shared._Moffstation.AacTablet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacPhraseButton : Button
{
    public AacPhraseButton()
    {
        RobustXamlLoader.Load(this);
    }

    public static AacPhraseButton Create(
        AacPhrase phrase,
        Action<AacPhrase> onPressed,
        int containerWidth,
        int numColumns
    )
    {
        var ret = new AacPhraseButton();
        ret.PhraseLabel.SetMessage(phrase.Phrase);
        ret.MaxSize = new Vector2(GetButtonWidth(containerWidth, numColumns));
        ret.OnPressed += _ => onPressed(phrase);
        return ret;
    }

    private static int GetButtonWidth(int parentWidth, int numColumns)
    {
        const int spaceWidth = 10;
        return (parentWidth - spaceWidth) / numColumns;
    }
}
