using Content.Shared._Moffstation.AacTablet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacPhraseButtonsGroup : BoxContainer
{
    public AacPhraseButtonsGroup()
    {
        RobustXamlLoader.Load(this);
    }

    public static AacPhraseButtonsGroup Create(
        AacPhraseGroup group,
        Action<AacPhrase> onPressed,
        int containerWidth
    ) => Create(group.Heading, group.Phrases, onPressed, containerWidth);

    public static AacPhraseButtonsGroup Create(
        string? heading,
        IEnumerable<AacPhrase> phrases,
        Action<AacPhrase> onPressed,
        int containerWidth
    )
    {
        var ret = new AacPhraseButtonsGroup();
        ret.Label.Text = heading;
        foreach (var phrase in phrases)
        {
            ret.ButtonGrid.AddChild(AacPhraseButton.Create(phrase, onPressed, containerWidth, ret.ButtonGrid.Columns));
        }

        return ret;
    }
}
