using System.Linq;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared._Moffstation.AacTablet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacPhraseSearchTab : BoxContainer
{
    private AacPhrase? _firstPhrase;

    public event Action<AacPhrase>? OnPhrasePressed;

    public event Func<string, (AacPhrase? shortestMatch, IEnumerable<(AacPhrase, IEnumerable<string> path)> allMatches)>
        ? Search;

    public AacPhraseSearchTab()
    {
        RobustXamlLoader.Load(this);

        SearchText.OnTextChanged += UpdateContent;
        SearchText.OnTextEntered += SendFirstPhraseAndClear;
    }

    private void UpdateContent(LineEdit.LineEditEventArgs args)
    {
        var width = this.GetControlOfType<AacWindow>(true).FirstOrDefault()?.MinWidth ?? 540;
        Content.Children.Clear();
        var (shortest, searchPhrases) = Search?.Invoke(args.Text) ?? (null, []);
        _firstPhrase = shortest;
        Content.Children.Add(
            AacPhraseButtonsGroup.Create(
                null,
                searchPhrases.Select(it => (it.Item1, (string?)string.Join(" > ", it.path))),
                OnPressed,
                (int)width
            )
        );
    }

    private void SendFirstPhraseAndClear(LineEdit.LineEditEventArgs args)
    {
        if (_firstPhrase is { } firstPhrase)
        {
            OnPressed(firstPhrase);
        }

        SearchText.Clear();
        Content.Children.Clear();
    }

    private void OnPressed(AacPhrase phrase)
    {
        OnPhrasePressed?.Invoke(phrase);
    }
}
