using System.Linq;
using Content.Shared._Moffstation.AacTablet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacPhraseButtonsGroup : BoxContainer
{
    public AacPhraseButtonsGroup()
    {
        RobustXamlLoader.Load(this);
    }

    public static AacPhraseButtonsGroup Create(
        AacPhraseGroup group,
        Action<AacPhrase> onPressed,
        int containerWidth
    ) => Create(group.Heading, group.Phrases.Select(it => (it, (string?)null)), onPressed, containerWidth);

    public static AacPhraseButtonsGroup Create(
        string? heading,
        IEnumerable<(AacPhrase, string? parenthetical)> phrases,
        Action<AacPhrase> onPressed,
        int containerWidth
    )
    {
        var ret = new AacPhraseButtonsGroup();

        if (string.IsNullOrWhiteSpace(heading))
        {
            ret.Label.Visible = false;
        }
        else
        {
            ret.Label.Text = heading;
            ret.Label.Visible = true;
        }

        foreach (var (phrase, parenthetical) in phrases)
        {
            ret.ButtonGrid.AddChild(
                AacPhraseButton.Create(
                    phrase,
                    parenthetical,
                    onPressed,
                    containerWidth,
                    ret.ButtonGrid.Columns
                )
            );
        }

        return ret;
    }
}
