using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.AacTablet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.AacTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AacWindow : FancyWindow
{
    [Dependency] private EntityManager _entMan = default!;

    public event Action<AacPhrase>? PhraseButtonPressed;

    private readonly List<AacPhrasePackPrototype> _packs = new();

    public AacWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SearchTab.OnPhrasePressed += OnButtonPressed;
        SearchTab.Search += search => _entMan.System<AacTabletSystem>().SearchPhrases(search, _packs);
        Tabs.SetTabTitle(0, Loc.GetString("aac-tab-search"));
    }

    public void SetAacPhrasePacks(IEnumerable<AacPhrasePackPrototype> packs)
    {
        _packs.Clear();
        _packs.AddRange(packs);

        foreach (var (index, tab) in _packs.SelectMany(pack => pack.Tabs).Index())
        {
            Tabs.AddChild(AacPhraseButtonsTab.Create(tab, OnButtonPressed, (int)MinWidth));
            Tabs.SetTabTitle(index + 1, tab.Heading);
        }
    }

    private void OnButtonPressed(AacPhrase phrase)
    {
        PhraseButtonPressed?.Invoke(phrase);
    }
}
