using System.Linq;
using System.Numerics;
using Content.Client._Moffstation.Voting.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Content.Shared._Moffstation.Voting.Components;
using Content.Shared._Moffstation.Voting.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESVotingWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly MoffVoteEntrySystem _vote;

    private List<Entity<MoffVoteEntryComponent>> _lastEntries = new();

    public event Action<Entity<ESVoteComponent>, ESVoteOption>? OnVoteChanged;

    public ESVotingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _vote = _entityManager.System<MoffVoteEntrySystem>();
    }

    public void Update(EntityUid owner)
    {
        var entries = _vote.EnumerateEntries().ToList();

        if (entries.Count != _lastEntries.Count || entries.Intersect(_lastEntries).Count() != entries.Count)
        {
            this.Open();
            VotesContainer.Children.Clear();
            foreach (var entry in entries)
            {
                if (_entityManager.HasComponent<ESVoteComponent>(entry))
                {
                    var voteControl = new ESVoteControl
                    {
                        Vote = entry,
                    };
                    voteControl.OnVoteChanged += (arg1, arg2, _) => OnVoteChanged?.Invoke(arg1, arg2);
                    VotesContainer.AddChild(voteControl);
                }

                if (_entityManager.HasComponent<MoffEnrollEventComponent>(entry))
                {
                    var voteControl = new MoffEnrollControl
                    {
                        Enroller = entry,
                    };
                    // voteControl.OnVoteChanged += (arg1, arg2, _) => OnVoteChanged?.Invoke(arg1, arg2);
                    VotesContainer.AddChild(voteControl);
                }
            }
        }

        _lastEntries = entries;

        foreach (var child in VotesContainer.Children)
        {
            if (child is ESVoteControl ctrl)
            {
                var comp = _entityManager.GetComponent<ESVoteComponent>(ctrl.Vote);
                ctrl.Update((ctrl.Vote, comp), owner);
            }
        }
    }
}

