using System.Linq;
using System.Numerics;
using Content.Client._Moffstation.Voting.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Content.Shared._Moffstation.Voting.Components;
using Content.Shared._Moffstation.Voting.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

// Moffstation - we rewrote alot of this for
[GenerateTypedNameReferences]
public sealed partial class ESVotingWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly MoffVoteEntrySystem _vote;

    private List<Entity<MoffVoteEntryComponent>> _lastEntries = new();

    public event Action<Entity<ESVoteComponent>, ESVoteOption>? OnVoteChanged;

    public ESVotingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _vote = _entityManager.System<MoffVoteEntrySystem>();
    }

    public void Update(EntityUid owner)
    {
        var entries = _vote.EnumerateEntries().ToList();

        if (entries.Count != _lastEntries.Count || entries.Intersect(_lastEntries).Count() != entries.Count)
        {
            VotesContainer.Children.Clear();
            foreach (var entry in entries)
            {
                if (GenerateControl(entry) is not { } control)
                    continue;
                VotesContainer.AddChild(control);
            }
        }

        _lastEntries = entries;

        foreach (var child in VotesContainer.Children)
        {
            switch (child)
            {
                case ESVoteControl ctrl:
                {
                    var comp = _entityManager.GetComponent<ESVoteComponent>(ctrl.Vote);
                    ctrl.Update((ctrl.Vote, comp), owner);
                    break;
                }
                case MoffEnrollControl ctrl:
                {
                    var comp = _entityManager.GetComponent<MoffEnrollEventComponent>(ctrl.Enroller);
                    ctrl.Update((ctrl.Enroller, comp), owner);
                    break;
                }
            }
        }
    }

    private Control? GenerateControl(Entity<MoffVoteEntryComponent> ent)
    {
        if (_entityManager.HasComponent<ESVoteComponent>(ent.Owner))
        {
            var control = new ESVoteControl
            {
                Vote = ent.Owner,
            };
            control.OnVoteChanged += (arg1, arg2, _) => OnVoteChanged?.Invoke(arg1, arg2);
            return control;
        }

        if (_entityManager.HasComponent<MoffEnrollEventComponent>(ent.Owner))
        {
            var control = new MoffEnrollControl
            {
                Enroller = ent.Owner,
            };
            return control;
        }
        return null;
    }
}

