using System.Linq;
using System.Numerics;
using Content.Client._Moffstation.Voting.Ui;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Content.Shared._Moffstation.Voting.Components;
using Content.Shared._Moffstation.Voting.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Voting.Ui;

// Moffstation - we rewrote alot of this for
[GenerateTypedNameReferences]
public sealed partial class ESVotingWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly MoffVoteEntrySystem _vote;

    private List<Entity<MoffVoteEntryComponent>> _lastEntries = new();
    public event Action<Entity<ESVoteComponent>, bool>? OnVoteChanged;

    // Moffstation - matched against in declaration order to build the control for a vote entry
    private readonly List<(Func<EntityUid, bool> Matches, Func<EntityUid, IVoteEntryControl> Create)> _controlFactories;

    public ESVotingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _vote = _entityManager.System<MoffVoteEntrySystem>();

        _controlFactories =
        [
            (uid => _entityManager.HasComponent<ESVoteComponent>(uid), uid => new ESVoteControl(uid)),
            (uid => _entityManager.HasComponent<MoffEnrollEventComponent>(uid), uid => new MoffEnrollControl(uid)),
        ];
    }

    public void Update(EntityUid owner)
    {
        var entries = _vote.EnumerateEntries().ToList();

        if (entries.Count != _lastEntries.Count || entries.Intersect(_lastEntries).Count() != entries.Count)
        {
            VotesContainer.Children.Clear();
            foreach (var entry in entries)
            {
                if (GenerateControl(entry) is not { } control)
                    continue;
                VotesContainer.AddChild(control);
            }
        }

        _lastEntries = entries;

        foreach (var child in VotesContainer.Children)
        {
            if (child is IVoteEntryControl ctrl)
                ctrl.Update(owner);
        }
        // PB and B
        VotesContainer.InvalidateMeasure();
    }

    private Control? GenerateControl(Entity<MoffVoteEntryComponent> ent)
    {
        foreach (var (matches, create) in _controlFactories)
        {
            if (matches(ent.Owner))
                return (Control) create(ent.Owner);
        }
        return null;
    }
}

