using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterMessageBubble : BoxContainer
{
    private static readonly Color OwnBgColor = new(0.08f, 0.12f, 0.22f);
    private static readonly Color OtherBgColor = new(0.13f, 0.14f, 0.16f);
    private static readonly Color BorderColor = new(0.2f, 0.2f, 0.22f);
    private static readonly Color OverflowCountColor = new(0.6f, 0.6f, 0.6f);
    private static readonly Vector2 SeenIconSize = new(18, 18);
    private static readonly Thickness SeenIconMargin = new(0, 0, 1, 0);

    // Beyond this many actual readers, the last slot becomes a "+N" count instead of another avatar -
    // a long group chat shouldn't grow this row without bound.
    private const int MaxVisibleSeenAvatars = 4;

    // Shared across every bubble instance (one gets created per message rendered) instead of resolving
    // IoC and rebuilding these on every single message.
    private static Texture? _cachedSeenIcon;
    private static VectorFont? _cachedOverflowCountFont;

    private readonly StyleBoxFlat _bubbleStyle;
    private readonly Texture _seenIcon;
    private readonly VectorFont _overflowCountFont;

    public string SenderName
    {
        set => SenderLabel.Text = value;
    }

    public string Message
    {
        set => MessageLabel.Text = value;
    }

    public TimeSpan Timestamp
    {
        set => TimestampLabel.Text = TimeSpan.FromSeconds(Math.Truncate(value.TotalSeconds)).ToString();
    }

    public bool IsOwn
    {
        set
        {
            HorizontalAlignment = value ? HAlignment.Right : HAlignment.Left;
            SenderRow.Visible = !value;
            _bubbleStyle.BackgroundColor = value ? OwnBgColor : OtherBgColor;
        }
    }

    public bool DeliveryFailed
    {
        set => FailedLabel.Visible = value;
    }

    public Texture? ProfilePicture
    {
        set
        {
            if (value == null)
                return;

            AvatarTexture.Visible = true;
            AvatarTexture.Texture = value;
        }
    }

    public bool IsNew
    {
        set
        {
            _bubbleStyle.BorderColor = value
                ? new Color(0.35f, 0.7f, 0.35f)
                : BorderColor;
        }
    }

    public IReadOnlyList<Texture> SeenByAvatars
    {
        set
        {
            SeenAvatarsRow.RemoveAllChildren();

            if (value.Count == 0)
            {
                SeenAvatarsRow.Visible = false;
                return;
            }

            TextureRect MakeIcon(Texture texture) => new()
            {
                Texture = texture,
                Stretch = TextureRect.StretchMode.Scale,
                SetSize = SeenIconSize,
                Margin = SeenIconMargin,
                VerticalAlignment = VAlignment.Top,
            };

            SeenAvatarsRow.AddChild(MakeIcon(_seenIcon));

            // Leave one slot free for a "+N" count if there isn't room to show everyone as their own
            // avatar.
            var overflow = value.Count > MaxVisibleSeenAvatars;
            var avatarsToShow = overflow ? MaxVisibleSeenAvatars - 1 : value.Count;

            for (var i = 0; i < avatarsToShow; i++)
                SeenAvatarsRow.AddChild(MakeIcon(value[i]));

            if (overflow)
            {
                var remaining = Math.Min(value.Count - avatarsToShow, 99);
                SeenAvatarsRow.AddChild(new Label
                {
                    Text = $"+{remaining}",
                    FontColorOverride = OverflowCountColor,
                    FontOverride = _overflowCountFont,
                    VerticalAlignment = VAlignment.Top,
                });
            }

            SeenAvatarsRow.Visible = true;
        }
    }

    public ChitterMessageBubble()
    {
        RobustXamlLoader.Load(this);

        if (_cachedSeenIcon == null || _cachedOverflowCountFont == null)
        {
            var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
            _cachedSeenIcon = spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath("_Moffstation/Chitter/Icons/chitter_status_icons.rsi"), "seen"));

            // Matches the icon size so the overflow "+N" count doesn't visually dwarf the avatars next to it.
            var resourceCache = IoCManager.Resolve<IResourceCache>();
            _cachedOverflowCountFont = new VectorFont(resourceCache.GetResource<FontResource>("/Fonts/Sysfont/Sysfont-Regular.otf"), (int)SeenIconSize.X);
        }

        _seenIcon = _cachedSeenIcon;
        _overflowCountFont = _cachedOverflowCountFont;

        _bubbleStyle = new StyleBoxFlat
        {
            BackgroundColor = OtherBgColor,
            BorderColor = BorderColor,
            BorderThickness = new Thickness(1),
        };
        BubbleBackground.PanelOverride = _bubbleStyle;
    }
}
