using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Content.Shared._Moffstation.Chitter;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterUiFragment : BoxContainer
{
    private ChitterUiState _currentState = new();
    private Guid? _selectedChatId;
    private ChitterManageChatView? _openManageChatView;
    private readonly IPrototypeManager _prototypeManager;
    private readonly SpriteSystem _spriteSystem;

    public Action<ChitterUiMessageType, Guid?, uint?, List<uint>?, string?, string?, string?>? OnUiMessage;

    public ChitterUiFragment()
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        _spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        NewChatButton.OnPressed += _ => ShowNewChat();
        ProfileButton.OnPressed += _ => ShowProfile();
        SettingsButton.OnPressed += _ => ShowManageChat();
        SendButton.OnPressed += _ => SendCurrentMessage();
        MessageInput.OnTextEntered += _ => SendCurrentMessage();
    }

    public void UpdateState(ChitterUiState state)
    {
        _currentState = state;

        if (!state.HasIdCard)
        {
            WarningBanner.Visible = true;
            WarningLabel.Text = Loc.GetString("chitter-no-account");
            ChatView.Visible = false;
            NoChatPlaceholder.Visible = true;
            NewChatButton.Disabled = true;
            ProfileButton.Disabled = true;
            SettingsButton.Disabled = true;
            return;
        }

        if (!state.ServerOnline && state.HasIdCard)
        {
            WarningBanner.Visible = true;
            WarningLabel.Text = Loc.GetString("chitter-server-offline");
        }
        else
        {
            WarningBanner.Visible = false;
        }

        NewChatButton.Disabled = false;
        ProfileButton.Disabled = false;
        SettingsButton.Disabled = false;

        PlayerName.Text = state.OwnName;
        PlayerJob.Text = state.OwnJob;
        PlayerChitterId.Text = $"#{state.OwnNumber:D4}";
        if (!string.IsNullOrEmpty(state.OwnProfilePicture) &&
            _prototypeManager.TryIndex<ChitterAvatarPrototype>(state.OwnProfilePicture, out var avatar))
        {
            ProfileButton.TextureNormal = _spriteSystem.Frame0(avatar.Icon);
        }

        PopulateChatList(state);

        // Keep an open manage-chat overlay in sync with the server's authoritative participant list
        // instead of predicting the change locally (which could drift if the server ever rejects it).
        if (_openManageChatView != null && state.CurrentChat != null && state.CurrentChat.ChatId == _selectedChatId)
            _openManageChatView.UpdateData(state.CurrentChat, state.Contacts);

        if (OverlayContainer.Visible)
            return;

        if (state.CurrentChat != null)
        {
            _selectedChatId = state.CurrentChat.ChatId;
            ShowChatView(state.CurrentChat);
        }
        else if (_selectedChatId != null && state.Chats.Any(c => c.ChatId == _selectedChatId))
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.SelectChat, _selectedChatId, null, null, null, null, null);
        }
        else
        {
            NoChatPlaceholder.Visible = true;
            ChatView.Visible = false;
        }
    }

    private void ShowOverlay(Control view)
    {
        MainContent.Visible = false;
        OverlayContainer.RemoveAllChildren();
        OverlayContainer.AddChild(view);
        OverlayContainer.Visible = true;
    }

    private void HideOverlay()
    {
        OverlayContainer.Visible = false;
        OverlayContainer.RemoveAllChildren();
        MainContent.Visible = true;
        _openManageChatView = null;
    }

    private void PopulateChatList(ChitterUiState state)
    {
        ChatListContainer.RemoveAllChildren();

        foreach (var chat in state.Chats)
        {
            var entry = new ChitterChatListEntry
            {
                DisplayName = chat.DisplayName,
                LastMessage = chat.LastMessage,
                HasUnread = chat.HasUnread,
                UnreadCount = chat.UnreadCount,
                Selected = chat.ChatId == _selectedChatId,
            };

            var capturedId = chat.ChatId;
            entry.OnPressed += () =>
            {
                _selectedChatId = capturedId;
                OnUiMessage?.Invoke(ChitterUiMessageType.SelectChat, capturedId, null, null, null, null, null);
            };

            ChatListContainer.AddChild(entry);
        }
    }

    private void ShowChatView(ChatDetail? detail)
    {
        HideOverlay();

        if (detail == null)
        {
            NoChatPlaceholder.Visible = true;
            ChatView.Visible = false;
            return;
        }

        NoChatPlaceholder.Visible = false;
        ChatView.Visible = true;

        MessageContainer.RemoveAllChildren();

        foreach (var msg in detail.Messages)
        {
            Texture? profilePicture = null;
            if (!string.IsNullOrEmpty(msg.SenderProfilePicture) &&
                _prototypeManager.TryIndex<ChitterAvatarPrototype>(msg.SenderProfilePicture, out var avatarProto))
            {
                profilePicture = _spriteSystem.Frame0(avatarProto.Icon);
            }

            var bubble = new ChitterMessageBubble
            {
                SenderName = msg.SenderName,
                Message = msg.Content,
                Timestamp = msg.Timestamp,
                IsOwn = msg.IsOwn,
                DeliveryFailed = msg.DeliveryFailed,
                ProfilePicture = profilePicture,
                IsNew = msg.IsNew,
            };
            MessageContainer.AddChild(bubble);
        }

        IoCManager.Resolve<IUserInterfaceManager>().DeferAction(() =>
            ChatView.VScrollTarget = float.MaxValue);
    }

    private void ShowManageChat()
    {
        if (_currentState.CurrentChat == null)
            return;

        var chatId = _currentState.CurrentChat.ChatId;
        var view = new ChitterManageChatView(_currentState.CurrentChat, _currentState.Contacts);
        _openManageChatView = view;
        view.OnBack += HideOverlay;
        // Add/remove participant just fire the request; the view is refreshed from the server's
        // next authoritative state push (see UpdateState) rather than predicted locally here.
        view.OnAddParticipant += (id) =>
            OnUiMessage?.Invoke(ChitterUiMessageType.AddParticipant, chatId, id, null, null, null, null);
        view.OnRemoveParticipant += (id) =>
            OnUiMessage?.Invoke(ChitterUiMessageType.RemoveParticipant, chatId, id, null, null, null, null);
        view.OnLeaveChat += () =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.LeaveChat, chatId, null, null, null, null, null);
            HideOverlay();
            _selectedChatId = null;
        };
        view.OnArchive += () =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.ArchiveChat, chatId, null, null, null, null, null);
            HideOverlay();
            _selectedChatId = null;
        };
        view.OnRenameChat += (name) =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.RenameChat, chatId, null, null, null, null, name);
        };
        ShowOverlay(view);
    }

    private void ShowNewChat()
    {
        var contacts = _currentState.Contacts
            .Where(c => c.AccountId != _currentState.OwnNumber)
            .ToList();

        if (contacts.Count == 0)
            return;

        var view = new ChitterLookupView(contacts);
        view.OnChatCreated += (chatName, targetIds) =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.NewChat, null, null, targetIds, null, null, chatName);
            HideOverlay();
        };
        view.OnClose += HideOverlay;
        ShowOverlay(view);
    }

    private void ShowProfile()
    {
        var avatars = _prototypeManager.EnumeratePrototypes<ChitterAvatarPrototype>()
            .Where(p => !p.Hidden)
            .Select(p => (p.ID, _spriteSystem.Frame0(p.Icon)))
            .ToList();

        var view = new ChitterProfileView(avatars, _currentState.OwnProfilePicture);
        view.OnProfilePictureSelected += (id) =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.SetProfilePicture, null, null, null, null, id, null);
            HideOverlay();
        };
        view.OnClose += HideOverlay;
        ShowOverlay(view);
    }

    private void SendCurrentMessage()
    {
        var text = MessageInput.Text.Trim();
        if (string.IsNullOrEmpty(text) || _selectedChatId == null)
            return;

        OnUiMessage?.Invoke(ChitterUiMessageType.SendMessage, _selectedChatId, null, null, text, null, null);
        MessageInput.Text = "";
    }
}
