using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Content.Shared._Moffstation.Chitter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterPiUiFragment : BoxContainer
{
    private List<ChitterLogChat> _chats = [];
    private ChitterLogChat? _selected;

    public ChitterPiUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ChitterPiUiState state)
    {
        _chats = state.Chats;

        if (_selected != null)
            _selected = _chats.FirstOrDefault(c => c.ChatId == _selected.ChatId);

        HeaderLabel.Text = state.LastScanTime == null
            ? Loc.GetString("chitter-pi-no-scan")
            : Loc.GetString("chitter-pi-last-scanned", ("server", state.ScannedServerName));

        RebuildChatList();
        RebuildMessageList();
    }

    private void RebuildChatList()
    {
        ChatList.RemoveAllChildren();

        foreach (var chat in _chats.OrderByDescending(c => c.CreatedTime))
        {
            var names = string.Join(", ", chat.Participants.Select(p => p.Name));
            var label = string.IsNullOrWhiteSpace(chat.ChatName) ? names : chat.ChatName;
            if (chat.Archived)
                label = $"[{Loc.GetString("chitter-log-archived")}] {label}";

            var button = new Button
            {
                Text = label,
                ToolTip = names,
                HorizontalExpand = true,
                ClipText = true,
                Pressed = chat == _selected,
            };
            button.OnPressed += _ =>
            {
                _selected = chat;
                RebuildChatList();
                RebuildMessageList();
            };
            ChatList.AddChild(button);
        }

        if (ChatList.ChildCount == 0)
        {
            ChatList.AddChild(new Label
            {
                Text = Loc.GetString("chitter-log-no-chats"),
                FontColorOverride = Color.Gray,
            });
        }
    }

    private void RebuildMessageList()
    {
        MessageList.RemoveAllChildren();

        if (_selected == null)
        {
            DetailHeader.Text = Loc.GetString("chitter-log-select-chat");
            return;
        }

        var participantNames = string.Join(", ", _selected.Participants.Select(p => $"{p.Name} (#{p.AccountId:D4})"));
        DetailHeader.Text = string.IsNullOrWhiteSpace(_selected.ChatName)
            ? participantNames
            : $"{_selected.ChatName} — {participantNames}";

        foreach (var message in _selected.Messages)
        {
            var time = TimeSpan.FromSeconds(Math.Truncate(message.Timestamp.TotalSeconds)).ToString();
            var failedSuffix = message.DeliveryFailed ? $" ({Loc.GetString("chitter-log-delivery-failed")})" : "";

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 0, 0, 4),
            };

            row.AddChild(new Label
            {
                Text = $"[{time}] {message.SenderName} (#{message.SenderAccountId:D4}){failedSuffix}",
                FontColorOverride = Color.Gray,
            });
            row.AddChild(new Label
            {
                Text = message.Content,
            });

            MessageList.AddChild(row);
        }

        if (_selected.Messages.Count == 0)
        {
            MessageList.AddChild(new Label
            {
                Text = Loc.GetString("chitter-log-no-messages"),
                FontColorOverride = Color.Gray,
            });
        }
    }
}
