using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterProfileView : BoxContainer
{
    public event Action<string>? OnProfilePictureSelected;
    public event Action? OnClose;

    public ChitterProfileView()
    {
        RobustXamlLoader.Load(this);
    }

    public ChitterProfileView(List<(string Id, Texture Sprite)> avatars, string currentAvatarId) : this()
    {
        CloseProfileButton.OnPressed += _ => OnClose?.Invoke();

        foreach (var (id, sprite) in avatars)
        {
            var btn = new TextureButton
            {
                TextureNormal = sprite,
                MinSize = new Vector2(64, 64),
                SetSize = new Vector2(64, 64),
            };

            if (id == currentAvatarId)
            {
                var borderPanel = new PanelContainer
                {
                    MinSize = new Vector2(64, 64),
                    Children =
                    {
                        btn,
                    },
                };
                AvatarGrid.AddChild(borderPanel);
            }
            else
            {
                var capturedId = id;
                btn.OnPressed += _ =>
                {
                    OnProfilePictureSelected?.Invoke(capturedId);
                    OnClose?.Invoke();
                };
                AvatarGrid.AddChild(btn);
            }
        }
    }
}
