using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterMessageBubble : BoxContainer
{
    private static readonly Color OwnBgColor = new(0.08f, 0.12f, 0.22f);
    private static readonly Color OtherBgColor = new(0.13f, 0.14f, 0.16f);
    private static readonly Color BorderColor = new(0.2f, 0.2f, 0.22f);
    private readonly StyleBoxFlat _bubbleStyle;

    public string SenderName
    {
        set => SenderLabel.Text = value;
    }

    public string Message
    {
        set => MessageLabel.Text = value;
    }

    public TimeSpan Timestamp
    {
        set => TimestampLabel.Text = TimeSpan.FromSeconds(Math.Truncate(value.TotalSeconds)).ToString();
    }

    public bool IsOwn
    {
        set
        {
            HorizontalAlignment = value ? HAlignment.Right : HAlignment.Left;
            SenderRow.Visible = !value;
            _bubbleStyle.BackgroundColor = value ? OwnBgColor : OtherBgColor;
        }
    }

    public bool DeliveryFailed
    {
        set => FailedLabel.Visible = value;
    }

    public Texture? ProfilePicture
    {
        set
        {
            if (value == null)
                return;

            AvatarTexture.Visible = true;
            AvatarTexture.Texture = value;
        }
    }

    public bool IsNew
    {
        set
        {
            _bubbleStyle.BorderColor = value
                ? new Color(0.35f, 0.7f, 0.35f)
                : BorderColor;
        }
    }

    public ChitterMessageBubble()
    {
        RobustXamlLoader.Load(this);

        _bubbleStyle = new StyleBoxFlat
        {
            BackgroundColor = OtherBgColor,
            BorderColor = BorderColor,
            BorderThickness = new Thickness(1),
        };
        BubbleBackground.PanelOverride = _bubbleStyle;
    }
}
