using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Content.Shared._Moffstation.Chitter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterPiUiFragment : BoxContainer
{
    private List<ChitterLogChat> _chats = [];
    private ChitterLogChat? _selected;

    public ChitterPiUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ChitterPiUiState state)
    {
        _chats = state.Chats;

        if (_selected != null)
            _selected = _chats.FirstOrDefault(c => c.ChatId == _selected.ChatId);

        HeaderLabel.Text = state.LastScanTime == null
            ? Loc.GetString("chitter-pi-no-scan")
            : Loc.GetString("chitter-pi-last-scanned", ("server", state.ScannedServerName));

        RebuildChatList();
        RebuildMessageList();
    }

    private void RebuildChatList()
    {
        ChitterLogRenderer.RebuildChatList(ChatList, _chats, _selected, "", chat =>
        {
            _selected = chat;
            RebuildChatList();
            RebuildMessageList();
        });
    }

    private void RebuildMessageList()
    {
        ChitterLogRenderer.RebuildMessageList(MessageList, DetailHeader, _selected);
    }
}
