using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Input;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterChatListEntry : BoxContainer
{
    private static readonly Color DefaultBg = Color.FromHex("#1a1a1a");
    private static readonly Color HoverBg = Color.FromHex("#2a2a2a");
    private static readonly Color SelectedBg = Color.FromHex("#3a5a3a");

    private bool _selected;
    private bool _hovered;

    public string DisplayName
    {
        set => NameLabel.Text = value;
    }

    public string LastMessage
    {
        set => MessageLabel.Text = value;
    }

    public bool HasUnread
    {
        set => NameLabel.FontColorOverride = value ? Color.Green : null;
    }

    public int UnreadCount
    {
        set
        {
            UnreadCountLabel.Visible = value > 0;
            UnreadCountLabel.Text = $"({value})";
        }
    }

    public bool Selected
    {
        get => _selected;
        set
        {
            _selected = value;
            UpdateBackground();
        }
    }

    public event Action? OnPressed;

    public ChitterChatListEntry()
    {
        RobustXamlLoader.Load(this);

        MouseFilter = MouseFilterMode.Stop;

        OnMouseEntered += _ => { _hovered = true; UpdateBackground(); };
        OnMouseExited += _ => { _hovered = false; UpdateBackground(); };

        OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick || args.Function == EngineKeyFunctions.Use)
                OnPressed?.Invoke();
        };
    }

    private void UpdateBackground()
    {
        if (BackgroundPanel.PanelOverride is not StyleBoxFlat style)
            return;

        if (_selected)
            style.BackgroundColor = SelectedBg;
        else if (_hovered)
            style.BackgroundColor = HoverBg;
        else
            style.BackgroundColor = DefaultBg;
    }
}
