using System.Linq;
using System.Numerics;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterLookupView : BoxContainer
{
    private static readonly Vector2 BlockIconSize = new(20, 20);

    // Shared across every lookup view instance instead of resolving IoC and re-loading the icon each
    // time the New Chat / contacts overlay is opened.
    private static Texture? _cachedBlockIcon;

    private List<AccountEntry> _contacts = null!;
    private List<AccountEntry> _blockedContacts = null!;
    private HashSet<uint> _selectedIds = new();
    private bool _showingBlocked;
    private readonly Texture _blockIcon;

    public event Action<string?, List<uint>>? OnChatCreated;
    public event Action<uint>? OnBlockContact;
    public event Action<uint>? OnUnblockContact;
    public event Action? OnClose;

    public ChitterLookupView()
    {
        RobustXamlLoader.Load(this);

        _cachedBlockIcon ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>()
            .Frame0(new SpriteSpecifier.Rsi(new ResPath("_Moffstation/Chitter/Icons/chitter_status_icons.rsi"), "block"));
        _blockIcon = _cachedBlockIcon;
    }

    public ChitterLookupView(List<AccountEntry> contacts, List<AccountEntry> blockedContacts) : this()
    {
        _contacts = contacts;
        _blockedContacts = blockedContacts;

        CloseLookupButton.OnPressed += _ => OnClose?.Invoke();
        CreateChatButton.OnPressed += _ =>
        {
            if (_selectedIds.Count > 0)
            {
                var chatName = ChatNameInput.Text.Trim();
                OnChatCreated?.Invoke(string.IsNullOrEmpty(chatName) ? null : chatName, _selectedIds.ToList());
            }
        };

        ShowBlockedButton.OnToggled += args =>
        {
            _showingBlocked = args.Pressed;
            UpdateResults(SearchInput.Text.Trim().ToLower());
        };

        SearchInput.OnTextChanged += _ =>
        {
            var search = SearchInput.Text.Trim().ToLower();
            UpdateResults(search);
        };

        UpdateResults("");
    }

    // Called from ChitterUiFragment whenever a fresh ChitterUiState arrives while this view is still
    // open, so blocking/unblocking someone moves their row between lists immediately instead of only
    // taking effect the next time the overlay is reopened.
    public void UpdateData(List<AccountEntry> contacts, List<AccountEntry> blockedContacts)
    {
        _contacts = contacts;
        _blockedContacts = blockedContacts;
        _selectedIds.RemoveWhere(id => contacts.All(c => c.AccountId != id));
        UpdateResults(SearchInput.Text.Trim().ToLower());
    }

    private void UpdateResults(string search)
    {
        SearchResults.RemoveAllChildren();

        ChatNameInput.Visible = !_showingBlocked;
        CreateChatButton.Visible = !_showingBlocked;
        CreateChatButton.Disabled = _selectedIds.Count == 0;

        var source = _showingBlocked ? _blockedContacts : _contacts;
        if (source == null)
            return;

        var blockText = Loc.GetString("chitter-block");
        var unblockText = Loc.GetString("chitter-unblock");

        foreach (var contact in source)
        {
            var name = contact.Name ?? "";
            if (!string.IsNullOrEmpty(search) && !name.ToLower().Contains(search))
                continue;

            var displayName = string.IsNullOrEmpty(name)
                ? $"#{contact.AccountId:D4}"
                : $"{name} ({contact.JobTitle})";

            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            var capturedId = contact.AccountId;

            if (_showingBlocked)
            {
                row.AddChild(new Label { Text = displayName, HorizontalExpand = true, VerticalAlignment = VAlignment.Center });

                var unblockBtn = new Button { Text = unblockText };
                unblockBtn.OnPressed += _ => OnUnblockContact?.Invoke(capturedId);
                row.AddChild(unblockBtn);
            }
            else
            {
                var selectBtn = new Button
                {
                    Text = displayName,
                    HorizontalExpand = true,
                    ToggleMode = true,
                    Pressed = _selectedIds.Contains(capturedId),
                };
                selectBtn.OnToggled += args =>
                {
                    if (args.Pressed)
                        _selectedIds.Add(capturedId);
                    else
                        _selectedIds.Remove(capturedId);

                    CreateChatButton.Disabled = _selectedIds.Count == 0;
                };
                row.AddChild(selectBtn);

                var blockBtn = new TextureButton
                {
                    TextureNormal = _blockIcon,
                    SetSize = BlockIconSize,
                    ToolTip = blockText,
                    VerticalAlignment = VAlignment.Center,
                };
                blockBtn.OnPressed += _ => OnBlockContact?.Invoke(capturedId);
                row.AddChild(blockBtn);
            }

            SearchResults.AddChild(row);
        }
    }
}
