using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterManageChatView : BoxContainer
{
    private ChatDetail _chat = null!;
    private List<AccountEntry> _contacts = null!;

    public event Action? OnBack;
    public event Action<uint>? OnAddParticipant;
    public event Action<uint>? OnRemoveParticipant;
    public event Action? OnLeaveChat;
    public event Action? OnArchive;
    public event Action<string?>? OnRenameChat;

    public ChitterManageChatView()
    {
        RobustXamlLoader.Load(this);
    }

    public ChitterManageChatView(ChatDetail chat, List<AccountEntry> contacts) : this()
    {
        _chat = chat;
        _contacts = contacts;

        BackButton.OnPressed += _ => OnBack?.Invoke();
        LeaveChatButton.OnPressed += _ =>
        {
            OnLeaveChat?.Invoke();
            OnBack?.Invoke();
        };
        ArchiveChatButton.OnPressed += _ => OnArchive?.Invoke();

        ChatNameInput.Text = chat.ChatName;
        RenameButton.OnPressed += _ =>
        {
            var name = ChatNameInput.Text.Trim();
            OnRenameChat?.Invoke(string.IsNullOrEmpty(name) ? null : name);
        };

        PopulateParticipants();
    }

    public void RefreshState()
    {
        PopulateParticipants();
    }

    /// <summary>
    /// Replaces this view's chat/contacts data with a fresh server-authoritative copy and re-renders.
    /// </summary>
    public void UpdateData(ChatDetail chat, List<AccountEntry> contacts)
    {
        _chat = chat;
        _contacts = contacts;
        PopulateParticipants();
    }

    private void PopulateParticipants()
    {
        ParticipantsList.RemoveAllChildren();

        foreach (var participant in _chat.Participants)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
            };

            row.AddChild(new Label
            {
                Text = $"{participant.Name} ({participant.JobTitle})",
                HorizontalExpand = true,
            });

            var removeBtn = new Button
            {
                Text = Loc.GetString("chitter-remove"),
            };
            var capturedId = participant.AccountId;
            removeBtn.OnPressed += _ => OnRemoveParticipant?.Invoke(capturedId);
            row.AddChild(removeBtn);

            ParticipantsList.AddChild(row);
        }

        var addRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
        };

        addRow.AddChild(new Label
        {
            Text = Loc.GetString("chitter-add-participant"),
            HorizontalExpand = true,
        });

        var searchInput = new LineEdit
        {
            PlaceHolder = Loc.GetString("chitter-search-placeholder"),
            HorizontalExpand = true,
        };
        searchInput.OnTextChanged += _ =>
        {
            var search = searchInput.Text.Trim().ToLower();
            ShowSearchResults(search);
        };
        addRow.AddChild(searchInput);

        ParticipantsList.AddChild(addRow);
    }

    private void ShowSearchResults(string search)
    {
        foreach (var child in ParticipantsList.Children.ToList())
        {
            if (child is Button)
                ParticipantsList.RemoveChild(child);
        }

        if (string.IsNullOrEmpty(search))
            return;

        foreach (var contact in _contacts)
        {
            if (!contact.Name.ToLower().Contains(search))
                continue;

            if (_chat.Participants.Any(p => p.AccountId == contact.AccountId))
                continue;

            var contactBtn = new Button
            {
                Text = $"{contact.Name} (#{contact.AccountId:D4})",
                HorizontalExpand = true,
            };
            var capturedId = contact.AccountId;
            contactBtn.OnPressed += _ => OnAddParticipant?.Invoke(capturedId);
            ParticipantsList.AddChild(contactBtn);
        }
    }
}
