using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class TicketMasterUiFragment : BoxContainer
{
    private const int MaxTicketLength = 512;

    public Action<string, string, string>? OnTicketPrinted;
}
