using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class TicketMasterUiFragment : BoxContainer
{
    private const int MaxTicketLength = 512;

    public Action<string, string, string>? OnTicketPrinted;

    public TicketMasterUiFragment()
    {
        RobustXamlLoader.Load(this);
        PrintButton.OnPressed += _ => OnTicketPrinted?.Invoke(string.Empty, OffenderNameEdit.Text, Rope.Collapse(DescriptionEdit.TextRope));
    }
}
