using Content.Client._DV.CustomObjectiveSummary;
using Content.Client._Moffstation.ObjectivePicker;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CharacterMenu;

[GenerateTypedNameReferences]
public sealed partial class MoffCharacterWindow : DefaultWindow
{
    public MoffCharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddObjectiveButtons(int objectiveCount, bool canPickObjectives)
    {
        // Pinktexting
        if (objectiveCount > 0)
        {
            var button = new Button
            {
                StyleClasses = { "OpenBoth" },
                Text = Loc.GetString("custom-objective-button-text"),
                Margin = new Thickness(2, 2),
            };
            button.OnPressed += _ => UserInterfaceManager.GetUIController<CustomObjectiveSummaryUIController>().OpenWindow();
            Objectives.AddChild(button);
            return;
        }

        // No objectives label
        if (!canPickObjectives)
        {
            Objectives.AddChild(new Label
            {
                Text = Loc.GetString("character-info-no-objectives"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        // Objective picker button
        var objectivePickerButton = new Button
        {
            StyleClasses = { "OpenBoth" },
            Text = Loc.GetString("objective-picker-button"),
            Margin = new Thickness(2, 2),
        };
        objectivePickerButton.OnPressed += _ => UserInterfaceManager.GetUIController<ObjectivePickerUIController>().EnsureWindow();
        Objectives.AddChild(objectivePickerButton);
    }
}
