using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CharacterMenu;

[GenerateTypedNameReferences]
public sealed partial class MoffCharacterWindow : DefaultWindow
{
    public MoffCharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
