using System.Numerics;
using Content.Shared._Moffstation.Robotics.RoboticsConsole;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.RoboticsConsole;

[GenerateTypedNameReferences]
public sealed partial class MoffRoboticsConsoleButton : Button
{
    public event Action? OnDisablePressed = null;
    public event Action? OnDestroyPressed = null;

    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private SpriteSystem _sprite;

    public MoffRoboticsConsoleButton(BorgSensorStatus sensor, bool expanded, bool controlsEnabled)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entManager.System<SpriteSystem>();

        Update(sensor, expanded, controlsEnabled);
        DisableButton.OnPressed += _ => OnDisablePressed?.Invoke();
        DestroyButton.OnPressed += _ => OnDestroyPressed?.Invoke();
    }

    public void SetExpanded(bool expanded)
    {
        DetailedPanel.Visible =  expanded;
    }

    public void Update(BorgSensorStatus sensor, bool expanded, bool controlsEnabled)
    {
        NameLabel.Text = sensor.Name;
        CoordsIndicator.Modulate = sensor.Coordinates != null ? Color.LimeGreen : Color.DarkRed;
        StatusIcon.SetFromSpriteSpecifier(StatusSpecifier(sensor));
        StatusIcon.DisplayRect.TextureScale= new Vector2(2f, 2f);

        if (_prototypeManager.TryIndex<JobIconPrototype>(sensor.JobIcon, out var jobIcon))
            JobIcon.Texture= _sprite.Frame0(jobIcon.Icon);
        ChassisLabel.Text = sensor.ChassisName;

        BorgSprite.Texture = _sprite.Frame0(sensor.ChassisSprite!);

        var hpPercentColor =
            sensor.DamagePercentage switch {
                < 0.2f => "#FF6C7F", // red
                < 0.4f => "#EF973C", // orange
                < 0.6f => "#E8CB2D", // yellow
                < 0.8f => "#30CC19", // green
                _ => "#00D3B8" // cyan
            };

        var batteryColor =
            sensor.Charge switch {
                < 0.2f => "#FF6C7F", // red
                < 0.4f => "#EF973C", // orange
                < 0.6f => "#E8CB2D", // yellow
                < 0.8f => "#30CC19", // green
                _ => "#00D3B8" // cyan
            };

        BrainLabel.Text = Loc.GetString("robotics-console-brain", ("brain", sensor.HasBrain));
        IntegrityLabel.Text = Loc.GetString("robotics-console-hp",
            ("hp", (int)((1 - sensor.DamagePercentage??0) * 100f)),
            ("color", hpPercentColor)); // todo : make an "unknown" label or smthing
        BatteriesLabel.Text = Loc.GetString("robotics-console-battery",
            ("charge", (int)(sensor.Charge * 100f)),
            ("color", batteryColor));
        ModulesLabel.Text = Loc.GetString("robotics-console-modules", ("count", sensor.ModuleCount));

        OnPressed += _ => DetailedPanel.Visible = !DetailedPanel.Visible;

        DetailedPanel.Visible = expanded;

        DisableButton.Disabled = !controlsEnabled;
        DestroyButton.Disabled = !controlsEnabled;
    }

    private SpriteSpecifier StatusSpecifier(BorgSensorStatus sensor)
    {
        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "alive");

        if (!sensor.IsAlive)
        {
            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "dead");
        }
        else if (sensor.DamagePercentage != null)
        {
            var index = MathF.Round(4f * sensor.DamagePercentage.Value);
            if (index >= 5)
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "critical");
            else
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "health" + index);
        }

        return specifier;
    }
}
