using System.Numerics;
using Content.Shared._Moffstation.Robotics.RoboticsConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.RoboticsConsole;

[GenerateTypedNameReferences]
public sealed partial class MoffRoboticsConsoleButton : Button
{
    public MoffRoboticsConsoleButton(BorgSensorStatus sensorStatus, bool expanded)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = sensorStatus.Name;
        CoordsIndicator.Modulate = sensorStatus.Coordinates != null ? Color.LimeGreen : Color.DarkRed;
        StatusIcon.SetFromSpriteSpecifier(StatusSpecifier(sensorStatus));
        StatusIcon.DisplayRect.TextureScale= new Vector2(2f, 2f);

        OnPressed += _ => DetailedPanel.Visible = !DetailedPanel.Visible;

        DetailedPanel.Visible = expanded;
    }

    private SpriteSpecifier StatusSpecifier(BorgSensorStatus sensor)
    {
        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "alive");

        if (!sensor.IsAlive)
        {
            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "dead");
        }
        else if (sensor.DamagePercentage != null)
        {
            var index = MathF.Round(4f * sensor.DamagePercentage.Value);
            if (index >= 5)
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "critical");
            else
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "health" + index);
        }

        return specifier;
    }
}
