using System.Numerics;
using Content.Shared._Moffstation.Robotics.RoboticsConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.RoboticsConsole;

[GenerateTypedNameReferences]
public sealed partial class MoffRoboticsConsoleButton : Button
{
    [Dependency] private IEntityManager _entManager = default!;

    public MoffRoboticsConsoleButton(BorgSensorStatus sensor, bool expanded, bool controls)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var _sprite = _entManager.System<SpriteSystem>();

        NameLabel.Text = sensor.Name;
        CoordsIndicator.Modulate = sensor.Coordinates != null ? Color.LimeGreen : Color.DarkRed;
        StatusIcon.SetFromSpriteSpecifier(StatusSpecifier(sensor));
        StatusIcon.DisplayRect.TextureScale= new Vector2(2f, 2f);

        BorgSprite.Texture = _sprite.Frame0(sensor.ChassisSprite!);

        var hpPercentColor =
            sensor.DamagePercentage switch {
                < 0.2f => "#FF6C7F", // red
                < 0.4f => "#EF973C", // orange
                < 0.6f => "#E8CB2D", // yellow
                < 0.8f => "#30CC19", // green
                _ => "#00D3B8" // cyan
        };

        var batteryColor =
            sensor.Charge switch {
            < 0.2f => "#FF6C7F", // red
            < 0.4f => "#EF973C", // orange
            < 0.6f => "#E8CB2D", // yellow
            < 0.8f => "#30CC19", // green
            _ => "#00D3B8" // cyan
        };

        BrainLabel.Text = Loc.GetString("robotics-console-brain", ("brain", sensor.HasBrain));
        IntegrityLabel.Text = Loc.GetString("robotics-console-hp",
            ("hp", (int)((1 - sensor.DamagePercentage??0) * 100f)),
            ("color", hpPercentColor)); // todo : make an "unknown" label or smthing
        BatteriesLabel.Text = Loc.GetString("robotics-console-battery",
            ("charge", (int)(sensor.Charge * 100f)),
            ("color", batteryColor));
        ModulesLabel.Text = Loc.GetString("robotics-console-modules", ("count", sensor.ModuleCount));

        OnPressed += _ => DetailedPanel.Visible = !DetailedPanel.Visible;

        DetailedPanel.Visible = expanded;
    }

    public void SetExpanded(bool expanded)
    {
        DetailedPanel.Visible =  expanded;
    }

    private SpriteSpecifier StatusSpecifier(BorgSensorStatus sensor)
    {
        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "alive");

        if (!sensor.IsAlive)
        {
            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "dead");
        }
        else if (sensor.DamagePercentage != null)
        {
            var index = MathF.Round(4f * sensor.DamagePercentage.Value);
            if (index >= 5)
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "critical");
            else
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "health" + index);
        }

        return specifier;
    }
}
