using System.Linq;
using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Robotics.RoboticsConsole;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.RoboticsConsole;

[GenerateTypedNameReferences]
public sealed partial class MoffRoboticsConsoleWindow : FancyWindow
{
    public event Action<NetEntity>? OnDisablePressed;
    public event Action<NetEntity>? OnDestroyPressed;

    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private Texture blipTexture;
    private Texture borgBlipTexture;

    private NetEntity? _trackedEntity;

    Dictionary<NetEntity, MoffRoboticsConsoleButton> buttons = new();

    public MoffRoboticsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        _spriteSystem = _entManager.System<SpriteSystem>();

        blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
        borgBlipTexture = blipTexture; // change later.
    }

    public void Setup(EntityUid? mapUid, string? stationName)
    {
        NavMap.MapUid = mapUid;
        StationName.Text = stationName ?? Loc.GetString("crew-monitoring-ui-no-station-label");
        NavMap.ForceNavMapUpdate();
    }

    public void Update(MoffRoboticsConsoleState status)
    {
        foreach (var borg in status.Cyborgs)
        {
            if (! buttons.Keys.Contains(borg.OwnerUid))
                CreateSensor(borg, status.AllowBorgControl);
            else
                UpdateSensor(borg.OwnerUid, borg, status.AllowBorgControl);
        }

        foreach (var removed in buttons.Keys.Except(status.Cyborgs.Select(x => x.OwnerUid)))
        {
            RemoveSensor(removed);
        }

        NavMap.ForceNavMapUpdate();
    }

    private void CreateSensor(BorgSensorStatus sensor, bool controlsEnabled)
    {
        var button = new MoffRoboticsConsoleButton(sensor, sensor.OwnerUid == _trackedEntity, controlsEnabled);
        button.OnPressed += _ => SetFocus(sensor.OwnerUid);
        button.OnDisablePressed += () => OnDisablePressed?.Invoke(sensor.OwnerUid);
        button.OnDestroyPressed += () => OnDestroyPressed?.Invoke(sensor.OwnerUid);

        buttons.Add(sensor.OwnerUid, button);
        SensorsTable.AddChild(button);

        if (sensor.Coordinates is not { } coordinates || !NavMap.Visible)
            return;

        var blip = borgBlipTexture;
        if (_prototypeManager.TryIndex<JobIconPrototype>(sensor.JobIcon, out var jobIcon))
            blip = _spriteSystem.Frame0(jobIcon.Icon);

        NavMap.TrackedEntities.TryAdd(
            sensor.OwnerUid,
            new NavMapBlip(
                CoordinatesToLocal(coordinates),
                blip,
                Color.White,
                sensor.SuitSensorUid == _trackedEntity,
                true,
                4f));
    }

    private void UpdateSensor(NetEntity borg, BorgSensorStatus sensor, bool controlsEnabled)
    {
        if (!buttons.TryGetValue(borg, out var button))
            return;

        button.Update(sensor, _trackedEntity == borg, controlsEnabled);

        var blip = borgBlipTexture;
        if (_prototypeManager.TryIndex<JobIconPrototype>(sensor.JobIcon, out var jobIcon))
            blip = _spriteSystem.Frame0(jobIcon.Icon);

        if (sensor.Coordinates is { } coordinates)
        {
            if (NavMap.TrackedEntities.ContainsKey(borg))
            {
                var tick = NavMap.TrackedEntities[borg];
                tick.Coordinates = CoordinatesToLocal(coordinates);
                tick.Blinks = _trackedEntity == borg;
                NavMap.TrackedEntities[borg] = tick;
            }
            else
            {
                NavMap.TrackedEntities.TryAdd(
                    sensor.OwnerUid,
                    new NavMapBlip(
                        CoordinatesToLocal(coordinates),
                        blip,
                        Color.White,
                        sensor.SuitSensorUid == _trackedEntity,
                        true,
                        4f));
            }
        }
        else
        {
            NavMap.TrackedEntities.Remove(borg);
        }
    }

    private void RemoveSensor(NetEntity borg)
    {
        if (!buttons.TryGetValue(borg, out var button))
            return;

        SensorsTable.RemoveChild(button);
        NavMap.TrackedEntities.Remove(borg);
    }


    private EntityCoordinates CoordinatesToLocal(NetCoordinates refCoords)
    {
        return new EntityCoordinates(_entManager.GetEntity(refCoords.NetEntity), refCoords.X, refCoords.Y);
    }

    private void SetFocus(NetEntity entity)
    {
        if (_trackedEntity is {} old && buttons[old] is { } oldButton)
            oldButton.SetExpanded(false);

        _trackedEntity = entity == _trackedEntity ? null : entity;

        if (_trackedEntity is {} cur && buttons[cur] is { } curButton)
            curButton.SetExpanded(true);
    }
}
