using Content.Client.Pinpointer.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Robotics.RoboticsConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.RoboticsConsole;

[GenerateTypedNameReferences]
public sealed partial class MoffRoboticsConsoleWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly SharedTransformSystem _transformSystem;
    private readonly SpriteSystem _spriteSystem;

    private bool controlsEnabled = false;
    private Texture blipTexture;
    private Texture borgBlipTexture;

    private NetEntity? _trackedEntity;

    Dictionary<NetEntity, MoffRoboticsConsoleButton> buttons = new();

    public MoffRoboticsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        _transformSystem = _entManager.System<SharedTransformSystem>();
        _spriteSystem = _entManager.System<SpriteSystem>();

        blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
        borgBlipTexture = blipTexture; // change later.
    }

    public void Setup(EntityUid? mapUid, string? stationName, bool enableControls)
    {
        NavMap.MapUid = mapUid;
        StationName.Text = stationName ?? Loc.GetString("crew-monitoring-ui-no-station-label");
        controlsEnabled = enableControls;

        NavMap.ForceNavMapUpdate();
    }

    public void Update(MoffRoboticsConsoleState status)
    {
        ClearData();

        foreach (var sensor in status.Cyborgs)
        {
            DisplaySensor(sensor);
        }
    }

    private void ClearData()
    {
        buttons = new Dictionary<NetEntity, MoffRoboticsConsoleButton>();
        SensorsTable.RemoveAllChildren();
        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedEntities.Clear();
        NavMap.LocalizedNames.Clear();
    }

    private void DisplaySensor(BorgSensorStatus sensor)
    {
        var button = new MoffRoboticsConsoleButton(sensor, sensor.OwnerUid == _trackedEntity, controlsEnabled);
        button.OnPressed += _ =>
        {
            if (_trackedEntity == sensor.OwnerUid)
                _trackedEntity = null;
            else
                _trackedEntity = sensor.OwnerUid;
        };
        SensorsTable.AddChild(button);
        buttons[sensor.OwnerUid] = button;

        if (sensor.Coordinates is {} coordinates && NavMap.Visible)
        {
            NavMap.TrackedEntities.TryAdd(
                sensor.OwnerUid,
                new NavMapBlip(
                    CoordinatesToLocal(coordinates),
                    borgBlipTexture,
                    Color.White,
                    sensor.SuitSensorUid == _trackedEntity,
                    true,
                    4f));
        }
    }

    private EntityCoordinates CoordinatesToLocal(NetCoordinates refCoords)
    {
        var coordinates = new EntityCoordinates(_entManager.GetEntity(refCoords.NetEntity), refCoords.X, refCoords.Y);

        if (NavMap.MapUid != null)
        {
            return _transformSystem.WithEntityId(coordinates, (EntityUid)NavMap.MapUid);
        }
        else
        {
            return coordinates;
        }
    }

    private void SetFocus(NetEntity entity)
    {
        if (_trackedEntity is {} old && buttons[old] is { } oldButton)
            oldButton.SetExpanded(false);

        _trackedEntity = entity == _trackedEntity ? null : entity;

        if (_trackedEntity is {} cur && buttons[cur] is { } curButton)
            curButton.SetExpanded(true);
    }
}
