using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Chitter;

[GenerateTypedNameReferences]
public sealed partial class ChitterAiWindow : DefaultWindow
{
    public ChitterAiWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
