using System.Linq;
using Content.Client._Moffstation.CartridgeLoader.Cartridges;
using Content.Shared._Moffstation.Chitter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Chitter;

[GenerateTypedNameReferences]
public sealed partial class ChitterLogWindow : DefaultWindow
{
    private List<ChitterLogChat> _chats = [];
    private ChitterLogChat? _selected;

    public ChitterLogWindow()
    {
        RobustXamlLoader.Load(this);
        SearchInput.OnTextChanged += _ => RebuildChatList();
    }

    public void UpdateState(ChitterLogEuiState state)
    {
        _chats = state.Chats;

        // Keep the current selection (refreshed with new data) if it's still around.
        if (_selected != null)
            _selected = _chats.FirstOrDefault(c => c.ChatId == _selected.ChatId);

        RebuildChatList();
        RebuildMessageList();
    }

    private void RebuildChatList()
    {
        ChitterLogRenderer.RebuildChatList(ChatList, _chats, _selected, SearchInput.Text.Trim(), chat =>
        {
            _selected = chat;
            RebuildChatList();
            RebuildMessageList();
        });
    }

    private void RebuildMessageList()
    {
        ChitterLogRenderer.RebuildMessageList(MessageList, DetailHeader, _selected);
    }
}
