using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Objectives;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.ObjectivePicker;

[GenerateTypedNameReferences]
public sealed partial class ObjectivePickerWindow : FancyWindow
{
    [Dependency] private readonly IPlayerManager _players = default!;
    [Dependency] private readonly IEntityManager _entity = default!;

    private SpriteSystem _sprite;
    private SharedMindSystem _mind;

    public event Action<NetEntity>? OnSelected;
    public event Action<HashSet<NetEntity>, NetEntity>? OnSubmitted;

    public HashSet<NetEntity> SelectedObjectives;

    public ObjectivePickerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mind ??= _entity.System<SharedMindSystem>();
        _sprite ??= _entity.System<SpriteSystem>();
        SelectedObjectives ??= new HashSet<NetEntity>();


        _mind.TryGetMind(_players.LocalSession, out var mindUid, out var mindComp);

        if (!_entity.TryGetComponent<PotentialObjectivesComponent>(mindUid, out var potentialObjectivesComponent))
            return;

        foreach (var objective in potentialObjectivesComponent.ObjectiveOptions)
        {
            var button = new Button
            {
                ToggleMode = true,
            };

            var objectiveBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var icon = new TextureRect
            {
                Texture = _sprite.Frame0(objective.Value.Icon),
            };

            var objectiveText = new RichTextLabel
            {
                Text = objective.Value.Title,
                HorizontalAlignment = HAlignment.Left,
            };

            var objectiveCheckbox = new RichTextLabel
            {
                Text = "[ ]",
                HorizontalAlignment = HAlignment.Right,
            };

            objectiveBox.Children.Add(icon);
            objectiveBox.Children.Add(objectiveText);
            objectiveBox.Children.Add(objectiveCheckbox);
            button.Children.Add(objectiveBox);

            button.OnPressed += _ => OnSelected?.Invoke(objective.Key);
            ObjectiveList.Children.Add(button);
        }

        SubmitButton.OnPressed += _ => OnSubmitted?.Invoke(SelectedObjectives, _entity.GetNetEntity(mindUid));
    }
}
