using Content.Shared.Cargo.Prototypes;
using Content.Shared.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.ObjectivePicker
{
    [GenerateTypedNameReferences]
    public sealed partial class ObjectivePickerEntry : PanelContainer
    {
        public ObjectiveInfo? Objective { get; set; }

        public ObjectivePickerEntry()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
