using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Objectives;
using Content.Shared.Mind;
using Content.Shared.Objectives.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.ObjectivePicker;

[GenerateTypedNameReferences]
public sealed partial class ObjectivePickerWindow : FancyWindow
{
    [Dependency] private readonly IPlayerManager _players = default!;
    [Dependency] private readonly IEntityManager _entity = default!;

    private SpriteSystem _sprite;
    private SharedMindSystem _mind;

    public ObjectivePickerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mind ??= _entity.System<SharedMindSystem>();
        _sprite ??= _entity.System<SpriteSystem>();

        _mind.TryGetMind(_players.LocalSession, out var mindUid, out var mindComp);

        if (!_entity.TryGetComponent<PotentialObjectivesComponent>(mindUid, out var potentialObjectivesComponent))
            return;

        foreach (var objective in potentialObjectivesComponent.ObjectiveOptions)
        {
            var objectiveBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var icon = new TextureButton
            {
                TextureNormal = _sprite.Frame0(objective.info.Icon),
            };

            var objectiveText = new RichTextLabel
            {
                Text = objective.info.Title,
            };

            objectiveBox.Children.Add(icon);
            objectiveBox.Children.Add(objectiveText);
            ObjectiveList.Children.Add(objectiveBox);
        }
    }
}
