using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Objectives;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.ObjectivePicker;

[GenerateTypedNameReferences]
public sealed partial class ObjectivePickerWindow : FancyWindow
{
    [Dependency] private readonly IPlayerManager _players = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private SpriteSystem _sprite;
    private SharedMindSystem _mind;

    private float _updateTimer = 1.0f;
    private const float UpdateTime = 1.0f;

    public event Action<NetEntity>? OnSelected;
    public event Action<HashSet<NetEntity>, NetEntity>? OnSubmitted;
    public event Action<HashSet<NetEntity>, int>? OnRandomize;
    public event Action? OnClear;

    public HashSet<NetEntity> SelectedObjectives;

    public ObjectivePickerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mind ??= _entity.System<SharedMindSystem>();
        _sprite ??= _entity.System<SpriteSystem>();
        SelectedObjectives ??= new HashSet<NetEntity>();


        _mind.TryGetMind(_players.LocalSession, out var mindUid, out _);

        PopulateObjectives(mindUid);

        SubmitButton.OnPressed += _ => OnSubmitted?.Invoke(SelectedObjectives, _entity.GetNetEntity(mindUid));
        ClearButton.OnPressed += _ => OnClear?.Invoke();

        if (!_entity.TryGetComponent<PotentialObjectivesComponent>(mindUid, out var comp))
            return;
        RandomizeButton.OnPressed += _ => OnRandomize?.Invoke(comp.ObjectiveOptions.Keys.ToHashSet(), comp.MaxChoices);
    }

    private void PopulateObjectives(EntityUid mindUid)
    {
        ObjectiveList.Children.Clear();

        if (!_entity.TryGetComponent<PotentialObjectivesComponent>(mindUid, out var potentialObjectivesComponent))
            return;

        foreach (var objective in potentialObjectivesComponent.ObjectiveOptions)
        {
            var button = new Button
            {
                ToggleMode = true,
                Pressed = SelectedObjectives.Contains(objective.Key),
                Disabled = SelectedObjectives.Count >= potentialObjectivesComponent.MaxChoices && !SelectedObjectives.Contains(objective.Key),
            };

            var objectiveBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var icon = new TextureRect
            {
                Texture = _sprite.Frame0(objective.Value.Icon),
            };

            var objectiveText = new RichTextLabel
            {
                Text = objective.Value.Title,
                HorizontalAlignment = HAlignment.Left,
                HorizontalExpand = true,

            };

            SubmitButton.Disabled = SelectedObjectives.Count < potentialObjectivesComponent.MinChoices ||
                                    SelectedObjectives.Count > potentialObjectivesComponent.MaxChoices;

            SelectionTip.Text = Loc.GetString("objective-picker-window-select-tip",
                ("selected", SelectedObjectives.Count),
                ("max", potentialObjectivesComponent.MaxChoices));

            objectiveBox.Children.Add(icon);
            objectiveBox.Children.Add(objectiveText);
            button.Children.Add(objectiveBox);

            button.OnPressed += _ => OnSelected?.Invoke(objective.Key);
            ObjectiveList.Children.Add(button);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer += args.DeltaSeconds;

        if (_updateTimer >= UpdateTime)
        {
            _updateTimer -= UpdateTime;
            UpdateTimer();
        }
    }

    public void UpdateState()
    {
        _mind.TryGetMind(_players.LocalSession, out var mindUid, out _);
        PopulateObjectives(mindUid);
    }

    private void UpdateTimer()
    {
        _mind.TryGetMind(_players.LocalSession, out var mindUid, out _);

        if (!_entity.TryGetComponent<PotentialObjectivesComponent>(mindUid, out var comp))
            return;

        var timeLeft = comp.AutoSelectionTime - _timing.CurTime;

        if (comp.AutoSelectionTime < _timing.CurTime)
        {
            this.Close();
            return;
        }

        TimeLeftTip.Text = Loc.GetString("objective-picker-window-time-left",
            ("time", timeLeft.ToString(@"mm\:ss")));
    }
}
