using Content.Shared._Moffstation.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class MoffEnrollControl : PanelContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    public EntityUid Enroller { get; init; } = EntityUid.Invalid;
    private TimeSpan _endTime;

    public MoffEnrollControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Update(Entity<MoffEnrollEventComponent> ent, EntityUid owner)
    {
        if (!_entityManager.EntityExists(ent))
            return;

        var netOwner = _entityManager.GetNetEntity(owner);

        Progress.MinValue = (float) (ent.Comp.EndTime - ent.Comp.Duration).TotalSeconds;
        Progress.MaxValue = (float) ent.Comp.EndTime.TotalSeconds;
        _endTime = ent.Comp.EndTime;
        if (_timing.CurTime > _endTime)
        {
            Progress.Visible = false;
            TimeLabel.Visible = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;

        TimeLabel.Text = $"Time remaining: {_endTime - curTime:mm\\:ss}";
        Progress.Value = (float) curTime.TotalSeconds;
    }
}

