using System.Linq;
using Content.Client.Message;
using Content.Shared._Moffstation.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Moffstation.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class MoffEnrollControl : PanelContainer, IVoteEntryControl
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPlayerManager _player = default!;

    public EntityUid Enroller { get; }
    private TimeSpan _endTime;

    public MoffEnrollControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }
    public MoffEnrollControl(EntityUid enroller)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Enroller = enroller;

        if (!_entityManager.TryGetComponent<MoffEnrollEventComponent>(Enroller, out var comp))
            return;

        var enrolled = _entityManager.GetNetEntity(_player.LocalEntity) is { } netEntity
                       && comp.Enrolled.Contains(netEntity);

        EnrollButton.Pressed = enrolled;
        EnrollButton.OnPressed += args =>
        {
            EnrollButton.Text = args.Button.Pressed ? "Enrolled" : "Enroll";
            OnEnrollChanged?.Invoke(Enroller, args.Button.Pressed);
        };
    }

    public void Update(EntityUid owner)
    {
        if (!_entityManager.TryGetComponent<MoffEnrollEventComponent>(Enroller, out var comp))
            return;

        Update((Enroller, comp), owner);
    }

    private void Update(Entity<MoffEnrollEventComponent> ent, EntityUid owner)
    {

        var metadata = _entityManager.GetComponentOrNull<MetaDataComponent>(Enroller);
        var name = metadata?.EntityName ?? string.Empty;
        var desc = metadata?.EntityDescription ?? string.Empty;
        VoteNameLabel.SetMarkup(Loc.GetString("moff-vote-enroll-header-text-format",
            ("color", ent.Comp.TitleColor),
            ("title", name)));
        VoteDescriptionLabel.SetMarkup(Loc.GetString("moff-vote-enroll-header-desc-format",
            ("color", ent.Comp.DescriptionColor),
            ("desc", desc)));

        TimerProgress.MinValue = (float) (ent.Comp.EndTime - ent.Comp.Duration).TotalSeconds;
        TimerProgress.MaxValue = (float) ent.Comp.EndTime.TotalSeconds;
        _endTime = ent.Comp.EndTime;
        if (_timing.CurTime > _endTime)
        {
            TimerProgress.Visible = false;
            TimeLabel.Visible = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;

        TimeLabel.Text = $"Time remaining: {_endTime - curTime:mm\\:ss}";
        TimerProgress.Value = (float) curTime.TotalSeconds;
    }
}

