using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration.Logs;
using Content.Shared.Database;
using Content.Shared.Medical.SuitSensor;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiSensorControl : Button
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly SpriteSystem _spriteSystem;

    public Action<NetEntity>? TrackButtonClick;
    public Action<NetCoordinates>? WarpButtonClick;

    private Texture _blipTexture;

    public NetEntity SuitSensorUid;
    public NetCoordinates? SuitSensorCoordinates;
    public StationAiSensorControl(SuitSensorStatus status)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entManager.System<SpriteSystem>();
        _blipTexture =
            _spriteSystem.Frame0(
                new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));

        SuitSensorUid = status.SuitSensorUid;
        SuitSensorCoordinates = status.Coordinates;

        Disabled = status.Coordinates == null;
        WarpButton.Disabled =status.Coordinates == null;

        WarpButton.AddStyleClass(StyleClass.Highlight);

        InitStatus(status);
        InitJob(status);

        OnButtonUp += _ => TrackButtonClick?.Invoke(SuitSensorUid);
        WarpButton.OnButtonUp +=  _ =>
        {
            if (SuitSensorCoordinates is { } coordinates)
                WarpButtonClick?.Invoke(coordinates);
        };
    }

    public void SetTracked(bool value)
    {
        if (value)
            AddStyleClass(StyleClass.Positive);
        else
            RemoveStyleClass(StyleClass.Positive);
    }

    private void InitStatus(SuitSensorStatus status)
    {
        CoordsIndicator.Texture = _blipTexture;
        CoordsIndicator.Modulate = status.Coordinates != null ? Color.LimeGreen : Color.DarkRed;

        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "alive");
        if (!status.IsAlive)
        {
            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "dead");
        }
        else if (status.DamagePercentage != null)
        {
            var index = MathF.Round(4f * status.DamagePercentage.Value);

            if (index >= 5)
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "critical");

            else
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "health" + index);
        }
        HealthIndicator.SetFromSpriteSpecifier(specifier);
        HealthIndicator.DisplayRect.TextureScale = new Vector2(2f, 2f);

        NameLabel.Text = status.Name;
    }

    private void InitJob(SuitSensorStatus status)
    {
        if (_prototypeManager.TryIndex<JobIconPrototype>(status.JobIcon, out var jobIcon))
            JobIcon.Texture = _spriteSystem.Frame0(jobIcon.Icon);

        JobNameLabel.Text = status.Job;
    }

}
