using System.Linq;
using Content.Client.Pinpointer.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.SuitSensor;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Silicons.StationAi;


[GenerateTypedNameReferences]
public sealed partial class StationAiMonitorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly SharedTransformSystem _transformSystem;
    private readonly SpriteSystem _spriteSystem;

    private NetEntity? _trackedEntity;
    private bool _tryToScrollToListFocus;

    public Action<NetCoordinates>? GotoClicked;

    public StationAiMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _transformSystem = _entManager.System<SharedTransformSystem>();
        _spriteSystem = _entManager.System<SpriteSystem>();


        NavMap.TrackedEntitySelectedAction += netent => SetTrackedEntity(netent);
    }

    public void SetStation(string stationName, EntityUid? stationUid)
    {
        if (_entManager.TryGetComponent<TransformComponent>(stationUid, out var xform))
            NavMap.MapUid = xform.GridUid;

        else
            NavMap.Visible = false;

        StationName.AddStyleClass("LabelBig");
        StationName.Text = stationName;
        NavMap.ForceNavMapUpdate();
    }

    public void ShowSensors(List<SuitSensorStatus> sensors)
    {
        ClearOutDatedData();

        if (sensors.Count == 0)
        {
            NoServerLabel.Visible = true;
            return;
        }
        NoServerLabel.Visible = false;

        var sensorsData = GetUniqueSensorsData(sensors);
        PopulateSensorTable(sensorsData);
    }

    private void ClearOutDatedData()
    {
        SensorTable.RemoveAllChildren();
        NavMap.TrackedCoordinates.Clear();
        NavMap.TrackedEntities.Clear();
        NavMap.LocalizedNames.Clear();
    }

    private void PopulateSensorTable(List<SuitSensorStatus> sensors)
    {
        var orderedSensors = sensors.OrderBy(n => n.Name).ThenBy(j => j.Job);
        var departments = sensors.SelectMany(d => d.JobDepartments).Distinct().OrderBy(n => n);

        var assignedSensors = new HashSet<SuitSensorStatus>();

        foreach (var department in departments)
        {
            var departmentSensors = orderedSensors.Where(n => n.JobDepartments.Contains(department));

            if (departmentSensors == null || ! departmentSensors.Any())
                continue;

            PopulateDepartmentTable(department, departmentSensors);
            assignedSensors.UnionWith(departmentSensors);
        }

        PopulateDepartmentTable(null, orderedSensors.Except(assignedSensors));
    }

    private void PopulateDepartmentTable(string? department, IEnumerable<SuitSensorStatus> departmentSensors)
    {
        if (departmentSensors.Count() == 0)
            return;

        if (SensorTable.ChildCount != 0)
        {
            var spacer = new Control()
            {
                SetHeight = 20,
            };
            SensorTable.AddChild(spacer);
        }

        var departmentLabel = new RichTextLabel()
        {
            Margin = new Thickness(10, 0),
            HorizontalExpand = true,
        };
        departmentLabel.SetMessage(department ?? "Others");
        departmentLabel.StyleClasses.Add("font-large");

        SensorTable.AddChild(departmentLabel);

        foreach (var sensor in departmentSensors)
        {
            if (!string.IsNullOrEmpty(NameFilterEdit.Text)
                && !sensor.Name.Contains(NameFilterEdit.Text, StringComparison.CurrentCultureIgnoreCase)
                && !sensor.Job.Contains(NameFilterEdit.Text, StringComparison.CurrentCultureIgnoreCase))
                continue;

            var control = new StationAiSensorControl(sensor);
            control.WarpButtonClick += coords => GotoClicked?.Invoke(coords);
            control.TrackButtonClick += uid => SetTrackedEntity(uid);

            if (sensor.SuitSensorUid == _trackedEntity)
                control.SetTracked(true);

            SensorTable.AddChild(control);

            AddToNavMap(sensor);
        }
    }

    private List<SuitSensorStatus> GetUniqueSensorsData(List<SuitSensorStatus> sensors)
    {
        var datas = new Dictionary<NetEntity, SuitSensorStatus>();
        foreach (var sensor in sensors)
        {
            if (datas.TryGetValue(sensor.OwnerUid, out var available))
            {
                if (available.Coordinates != null && sensor.Coordinates == null)
                    continue;
                if (available.DamagePercentage != null && sensor.DamagePercentage == null)
                    continue;
            }
            datas[sensor.OwnerUid] = sensor;
        }
        return datas.Values.ToList();
    }

    private void AddToNavMap(SuitSensorStatus status)
    {
        if (status.Coordinates == null)
            return;

        if (!_prototypeManager.TryIndex<JobIconPrototype>(status.JobIcon, out var jobIcon))
            return;

        var coordinates = _entManager.GetCoordinates(status.Coordinates);
        if (coordinates is not { } coords)
            return;

        var blipTexture = _spriteSystem.Frame0(jobIcon.Icon);

        NavMap.TrackedEntities.TryAdd(
            status.SuitSensorUid,
            new NavMapBlip(
                CoordinatesToLocal(coords),
                _spriteSystem.Frame0(jobIcon.Icon),
                Color.White,
                status.SuitSensorUid == _trackedEntity,
                true,
                4f
            )
        );
    }

    private void SetTrackedEntity(NetEntity? netent)
    {
        var prevTracked =  _trackedEntity;
        _trackedEntity = netent;

        if (_trackedEntity == prevTracked)
            _trackedEntity = null;

        NavMap.Focus = _trackedEntity;

        _tryToScrollToListFocus = true;

        UpdateSensorTable(_trackedEntity, prevTracked);
    }

    private void UpdateSensorTable(NetEntity? currTrackedEntity, NetEntity? prevTrackedEntity)
    {
        foreach (var control in SensorTable.Children)
        {
            if (control is not StationAiSensorControl sensorControl)
                continue;

            if (sensorControl.SuitSensorUid == prevTrackedEntity)
            {
                sensorControl.SetTracked(false);
                if (NavMap.TrackedEntities.TryGetValue(sensorControl.SuitSensorUid, out var blip))
                {
                    blip = new NavMapBlip(
                        CoordinatesToLocal(blip.Coordinates),
                        blip.Texture,
                        Color.White,
                        false,
                        true,
                        4f);
                    NavMap.TrackedEntities[sensorControl.SuitSensorUid] = blip;
                }
            }

            else if (sensorControl.SuitSensorUid == currTrackedEntity)
            {
                sensorControl.SetTracked(true);
                if (NavMap.TrackedEntities.TryGetValue(sensorControl.SuitSensorUid, out var blip))
                {
                    blip = new NavMapBlip(
                        CoordinatesToLocal(blip.Coordinates),
                        blip.Texture,
                        Color.White,
                        true,
                        true,
                        4f);
                }

                if (sensorControl.SuitSensorCoordinates is NetCoordinates coordinates)
                {
                    NavMap.CenterToCoordinates(
                        new EntityCoordinates(
                            _entManager.GetEntity(sensorControl.SuitSensorUid),
                            coordinates.Position));
                    NavMap.TrackedEntities[sensorControl.SuitSensorUid] = blip;
                }
            }

        if (sensorControl.SuitSensorCoordinates is null)
                continue;

            if (NavMap.TrackedEntities.TryGetValue(sensorControl.SuitSensorUid, out var tracked))
            {
                tracked = new NavMapBlip(
                    CoordinatesToLocal(tracked.Coordinates),
                    tracked.Texture,
                    (currTrackedEntity == null || sensorControl.SuitSensorUid == currTrackedEntity) ? Color.LimeGreen : Color.LimeGreen * Color.DimGray,
                    sensorControl.SuitSensorUid == currTrackedEntity);
            }
        }
    }

    private EntityCoordinates CoordinatesToLocal(EntityCoordinates refCoords)
    {
        if (NavMap.MapUid != null)
        {
            return _transformSystem.WithEntityId(refCoords, (EntityUid)NavMap.MapUid);
        }
        else
        {
            return refCoords;
        }
    }

}
